import { useState } from 'react'
import { cn } from '../../../lib/cn'

import { saveApp } from '../../../server/registry'
import { GrafanaLogs } from '../../logs'
import { CAPTION } from '../../tokens'
import { Alert, AlertDescription } from '../../ui/alert'
import { Button } from '../../ui/button'
import { useAction } from '../../use-action'
import { GLASS } from '../../viz/board'
import {
  type AppRecord,
  GHOST_BTN,
  LEDE,
  SECTION_HEAD,
  SECTION_HEAD_SMALL,
  SegmentPicker,
} from '../shared'
import { TaskCard } from './card'
import { TaskEditor } from './editor'
import type { TaskDraft, TaskRow, TasksData } from './types'

/**
 * What this app runs on a clock.
 *
 * One card per declared task: what it is, when it runs (in words AND as the
 * raw `OnCalendar` string, because the sentence is a convenience and the
 * string is the contract), what it runs, and how its last run ended. The
 * output is read by unit, not by the app's container — see TaskLogs.
 */
export function Tasks({ app, td }: { app: AppRecord; td: TasksData }) {
  const { tasks, running } = td.tasks
  const readOnly = app.managedInNix

  // What the form is doing, as one value rather than two booleans that can
  // both be true: nothing, adding, or editing exactly one existing task.
  const [editor, setEditor] = useState<{ kind: 'add' } | { kind: 'edit'; id: string } | null>(null)
  const { run, busy: saving, error } = useAction()

  /**
   * Write the WHOLE list back, the way every other edit on this page writes a
   * field: straight to Postgres through `saveApp`, then invalidate so the
   * loader recomputes drift and the Apply bar lights.
   *
   * The whole list rather than one task because `updateApp` replaces the
   * app's task rows wholesale, so a partial send would be a deletion of
   * everything omitted. The refusal from the boundary is shown as it came
   * back: those sentences name the task and the rule, and are the same ones
   * the form shows while you type.
   */
  const write = (next: TaskDraft[]) => {
    run(() => saveApp({ data: { name: app.name, patch: { tasks: next } } }), {
      onDone: () => {
        setEditor(null)
      },
    })
  }

  const remove = (id: string) => {
    write(app.tasks.filter((t) => t.id !== id))
  }

  const submit = (draft: TaskDraft) => {
    write(
      editor?.kind === 'edit'
        ? app.tasks.map((t) => (t.id === editor.id ? draft : t))
        : [...app.tasks, draft],
    )
  }

  return (
    <>
      <p className={LEDE}>
        Each task is a systemd timer and service pair generated by the platform. It runs as{' '}
        <code>podman exec app-{app.name}</code> with the argv below — no shell, so nothing in an
        argument is interpreted — and a failed run mails, like every other scheduled job on this
        box.
      </p>
      {/* The sentence that keeps this tab honest. Everything below is a
          registry row; the timer is generated from site/apps.json, which only
          an Apply writes. */}
      <p className={cn(LEDE, 'mt-2')}>
        Nothing here exists on the box until the next Apply. Adding, editing or removing a task
        changes this app’s registry entry — the Apply is what writes <code>site/apps.json</code>,
        rebuilds, and creates or removes the units.
      </p>

      {!running && (
        <p className={cn(LEDE, 'text-danger')}>
          {app.name} is not set up yet, so it has no container to run a task inside. Tasks can be
          authored now; the timers exist once its first image is in and it is set up.
        </p>
      )}

      {error !== null && (
        <Alert variant="warning" className="mt-4 mb-0 text-foreground">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {tasks.length === 0 && editor === null && (
        <EmptyState
          app={app.name}
          readOnly={readOnly}
          onAdd={() => {
            setEditor({ kind: 'add' })
          }}
        />
      )}

      {tasks.length > 0 && (
        <ul className="mt-6 mr-0 mb-0 ml-0 flex list-none flex-col gap-3 p-0">
          {tasks.map((t) =>
            editor?.kind === 'edit' && editor.id === t.id ? (
              <TaskEditor
                key={t.id}
                app={app.name}
                taken={app.tasks.filter((o) => o.id !== t.id).map((o) => o.id)}
                initial={app.tasks.find((o) => o.id === t.id)}
                busy={saving}
                onSubmit={submit}
                onCancel={() => {
                  setEditor(null)
                }}
              />
            ) : (
              <TaskCard
                key={t.id}
                app={app.name}
                task={t}
                running={running}
                readOnly={readOnly || editor !== null}
                busy={saving}
                onEdit={() => {
                  setEditor({ kind: 'edit', id: t.id })
                }}
                onRemove={() => {
                  remove(t.id)
                }}
              />
            ),
          )}
        </ul>
      )}

      {editor?.kind === 'add' && (
        <ul className="mt-6 mr-0 mb-0 ml-0 flex list-none flex-col gap-3 p-0">
          <TaskEditor
            app={app.name}
            taken={app.tasks.map((t) => t.id)}
            busy={saving}
            onSubmit={submit}
            onCancel={() => {
              setEditor(null)
            }}
          />
        </ul>
      )}

      {!readOnly && editor === null && tasks.length > 0 && (
        <Button
          type="button"
          variant="outline"
          size="sm"
          className={cn(GHOST_BTN, 'mt-4')}
          disabled={saving}
          onClick={() => {
            setEditor({ kind: 'add' })
          }}
        >
          + Add a task
        </Button>
      )}

      {tasks.length > 0 && (
        <>
          <h2 className={SECTION_HEAD}>
            Output
            <span className={SECTION_HEAD_SMALL}>what the last runs wrote</span>
          </h2>
          <TaskLogs tasks={tasks} />
        </>
      )}
    </>
  )
}

/**
 * The tab an app has never used.
 *
 * It explains the thing before offering the button, because "no tasks" is not
 * a problem to fix — most apps want none — and an operator who has not met the
 * feature cannot tell from an empty list whether it is broken or simply empty.
 */
function EmptyState({
  app,
  readOnly,
  onAdd,
}: {
  app: string
  readOnly: boolean
  onAdd: () => void
}) {
  return (
    <div className={cn(GLASS, 'mt-6 border-dashed bg-transparent px-5 py-4 shadow-none')}>
      <p className="m-0 max-w-[74ch] text-[0.9rem] text-subdued">
        {app} runs nothing on a clock. A scheduled task is a command run inside this app’s own
        container on a systemd timer — a nightly digest, an hourly sync, a weekly prune — with its
        output in Loki and a mail if it fails.
      </p>
      {readOnly ? (
        <p className={cn(CAPTION, 'mt-2.5')}>
          This app is declared by hand in Nix, so its tasks are written there rather than here.
        </p>
      ) : (
        <Button type="button" size="sm" className="mt-3.5" onClick={onAdd}>
          Add the first task
        </Button>
      )}
    </div>
  )
}

/**
 * One log panel, with a picker, rather than one panel per task.
 *
 * Each panel is a cross-origin Grafana iframe that boots a whole app to draw
 * one log view, so a page with four tasks would pay for four of them before
 * anybody had asked to read any. The Loki selector is an exact `unit="…"`
 * match — there is no prefix form — so one panel means one chosen task.
 */
function TaskLogs({ tasks }: { tasks: TaskRow[] }) {
  const first = tasks[0] as TaskRow
  const [selected, setSelected] = useState(first.id)
  const shown = tasks.find((t) => t.id === selected) ?? first

  return (
    <>
      {tasks.length > 1 && (
        <SegmentPicker
          value={shown.id}
          onChange={setSelected}
          label="Task logs"
          className="mb-3 h-auto flex-wrap"
          options={tasks.map((t) => ({ value: t.id, label: t.id }))}
        />
      )}
      {/* `.service`, and the `unit` form of LogSource: a task is its own
          systemd unit (`app-<name>-task-<id>.service`), so alloy labels its
          lines with that unit and with no container at all. Asking for
          `container="app-<name>"` here would show the app's own log and
          silently omit every line the task wrote. */}
      <GrafanaLogs source={{ unit: `${shown.unit}.service` }} title={`${shown.id} output`} />
    </>
  )
}
