import { readFile } from 'node:fs/promises'
import {
  arrayOf,
  bool,
  type Decoder,
  decode,
  int,
  literal,
  nullable,
  num,
  obj,
  optional,
  recordOf,
  str,
} from '../lib/contract/decode'
import { REGISTRY_SCHEMA_VERSION } from '../lib/contract/version'
import { APP_STAGES, type AppStage } from '../lib/stage'
// The one number, in the module the editor can also load: a component may not
// import from host/, and the default a form fills in has to be the default the
// decoder applies.
import { DEFAULT_TASK_TIMEOUT_SEC } from '../lib/tasks'
import { env } from './env'

// What Nix last built, as handed to this container by stacks/daedalus/daedalus.nix.
//
// This is NOT a second source of truth — it is the *comparison* target. The
// database is authoritative for everything the UI edits; this file is what the
// running system was actually built from. Where they differ, the app has
// pending changes that no Apply has shipped yet, and the UI says so rather
// than pretending the DB is live.
//
// It is a /nix/store path, so it can only change via a rebuild, and a rebuild
// restarts this container with the new one. There is no cache to invalidate.

// The ladder itself lives in lib/stage.ts, which the browser can also load.
// Re-exported here because this module is where the registry's shape is
// written down, and a decoder's neighbours are where callers look for it.
export type { AppStage }

export type ManifestEnvVar = { key: string; value: string; note?: string | null }

/**
 * cgroup v2 caps. null on any field = uncapped, which is the platform default
 * — see the `resources` option in stacks/apps/apps.nix for what each one
 * actually enforces and where the flag names lie about it.
 */
type ManifestResources = {
  cpus: number | null
  memoryMb: number | null
  pids: number | null
}

const NO_RESOURCES: ManifestResources = { cpus: null, memoryMb: null, pids: null }

/**
 * One scheduled task: a systemd timer + service pair named
 * `app-<name>-task-<id>`, generated by stacks/apps from this entry.
 *
 * `schedule` is a CONCRETE `OnCalendar` string, never a bare `hourly`/`daily`
 * — the app expands the presets before writing apps.json (lib/tasks.ts), so
 * nix does no arithmetic and the UI can name the exact minute a task runs.
 * `command` is argv, run as `podman exec app-<name> <argv>` with no shell in
 * between, so no value in it has anything to escape out of.
 */
export type ManifestTask = {
  id: string
  schedule: string
  command: string[]
  timeoutSec: number
}

export type ManifestApp = {
  stage: AppStage
  sourceMode?: 'registry' | 'local'
  postgres: boolean
  storage: boolean
  litellm: boolean
  prometheus: boolean
  /** null = `<name>.<baseDomain>`. Exactly one label under it — see apps.nix. */
  hostname?: string | null
  /**
   * The freeze switch. Absent (hand-written entries like daedalus's
   * self.json) = the platform default, `sourceMode === 'registry'` — the
   * same rule stacks/apps/apps.nix applies to `deploy.enable`.
   */
  deploy?: { enable: boolean } | null
  image: string | null
  egress: { container: string; hostPort: number } | null
  env: ManifestEnvVar[]
  auth: {
    mode: 'none' | 'proxy' | 'native'
    healthPath?: string | null
    isolated?: boolean
    allowedGroups?: string[] | null
    bypassRule?: string | null
  }
  presentation: { description: string }
  /** Optional so an apps.json predating the field still parses. */
  resources?: ManifestResources
  /** Same rule as `resources`: absent in a file written before tasks existed. */
  tasks?: ManifestTask[]
  notes?: Record<string, string>
}

// The publish/network/jobs registries moved to the /export domains
// (src/host/contract/domains/); the accessors below keep their names and
// delegate. What remains OF the manifest is the app-registry contract:
export type NixManifest = {
  schemaVersion: number
  registry: { schemaVersion: number; apps: Record<string, ManifestApp> }
  nixManaged: Record<string, ManifestApp>
  /**
   * Apps with a tracked `site/vault/apps/<name>-env.sops`.
   *
   * A fact, not a setting — the file existing is the only thing that decides
   * whether an app gets operator secrets, so there is nothing for the database
   * to hold an opinion about and nothing to drift. It arrives here rather than
   * through the registry export for exactly that reason: `apps.json` carries
   * what daedalus decides, this manifest carries what Nix found.
   */
  operatorSecretApps: string[]
}

/**
 * Every app Nix knows about, tagged with whether daedalus may edit it.
 *
 * `operatorSecrets` is resolved here from `operatorSecretApps` so callers see
 * one shape per app instead of having to remember which facts live in which
 * half of the manifest.
 */
export type ManifestEntry = ManifestApp & {
  name: string
  managedInNix: boolean
  operatorSecrets: boolean
}

// The runtime shape of one registry entry. Optional keys decode to the same
// normalised defaults every consumer already applied by hand (`?? null`,
// `?? {}`), so a file from an older writer parses and a malformed one names
// its broken path instead of surfacing as a crash three renders later.
const ns = optional(nullable(str), null)
const nn = optional(nullable(num), null)

const manifestApp: Decoder<ManifestApp> = obj({
  // From the tuple, so a rung added to the ladder is decodable here without a
  // second edit — and a file Nix accepts can never fail to parse here.
  stage: literal(...APP_STAGES),
  sourceMode: optional(literal('registry', 'local'), 'registry'),
  postgres: bool,
  storage: bool,
  litellm: bool,
  prometheus: bool,
  hostname: ns,
  deploy: optional(nullable(obj({ enable: bool })), null),
  image: ns,
  egress: optional(nullable(obj({ container: str, hostPort: num })), null),
  env: optional(arrayOf(obj({ key: str, value: str, note: ns })), []),
  auth: obj({
    mode: literal('none', 'proxy', 'native'),
    healthPath: ns,
    isolated: optional(bool, false),
    allowedGroups: optional(nullable(arrayOf(str)), null),
    bypassRule: ns,
  }),
  presentation: obj({ description: str }),
  resources: optional(obj({ cpus: nn, memoryMb: nn, pids: nn }), NO_RESOURCES),
  // Added the way `resources` was — `optional` here, `a.tasks or [ ]` in nix —
  // so an apps.json written before the field existed still parses and no
  // schemaVersion bump is owed. A bump is for a breaking reshape.
  //
  // `int` rather than `num` for the timeout: it becomes TimeoutStartSec on a
  // generated unit, and a fractional one is a file systemd would reject after
  // the Apply has already committed.
  tasks: optional(
    arrayOf(
      obj({
        id: str,
        schedule: str,
        command: arrayOf(str),
        timeoutSec: optional(int, DEFAULT_TASK_TIMEOUT_SEC),
      }),
    ),
    [],
  ),
  notes: optional(recordOf(str), {}),
})

const managedManifestShape = obj({
  schemaVersion: optional(num, 1),
  nixManaged: recordOf(manifestApp),
  operatorSecretApps: optional(arrayOf(str), []),
})

const registryFileShape = obj({
  schemaVersion: optional(num, 1),
  apps: recordOf(manifestApp),
})

/**
 * The committed registry (site/apps.json) as parsed JSON, decoded and held
 * to the one schema version this reader understands. The version is finally
 * read rather than assumed: the declarations.nix assertion guards the
 * rebuild; this guards the importer and the drift comparison. Exported for
 * the schema fixtures' test (host/contract/fixtures.test.ts), which is the
 * only other reader — a fixture that decodes but is the wrong version must
 * fail exactly the way the box's own file would.
 */
export function decodeRegistryFile(raw: unknown): NixManifest['registry'] {
  const registry = decode(registryFileShape, raw)
  if (registry.schemaVersion !== REGISTRY_SCHEMA_VERSION) {
    throw new Error(
      `applied registry declares schemaVersion ${String(registry.schemaVersion)}; this reader understands ${String(REGISTRY_SCHEMA_VERSION)}`,
    )
  }
  return registry
}

let cachedManaged: NixManifest['nixManaged'] | null = null
let cachedSecretApps: string[] | null = null

export async function readNixManifest(): Promise<NixManifest> {
  const managedPath = env.get('NIX_MANIFEST_PATH')
  const registryPath = env.get('NIX_REGISTRY_PATH')
  if (!managedPath || !registryPath) {
    throw new Error(
      'NIX_MANIFEST_PATH / NIX_REGISTRY_PATH are not set. Both are injected by ' +
        'stacks/daedalus/daedalus.nix — check the container env.',
    )
  }

  // The hand-written entries are a /nix/store path: immutable, and a change to
  // them restarts this container anyway, so caching for the process lifetime
  // is safe.
  if (cachedManaged === null || cachedSecretApps === null) {
    // decode() throws with the failing path. Loud on purpose: this file is
    // the app's core contract with nix, and a silently-empty manifest would
    // report every app as "not in the last Nix build".
    const parsed = decode(managedManifestShape, JSON.parse(await readFile(managedPath, 'utf8')))
    cachedManaged = parsed.nixManaged
    cachedSecretApps = parsed.operatorSecretApps
  }

  // The committed registry is NOT cached. It lives at a fixed path that
  // daedalus-registry-snapshot rewrites on every rebuild — which is precisely
  // what lets an Apply update it without restarting this app. Caching it would
  // reintroduce the restart by another name: the UI would keep reporting drift
  // against a registry that had already been applied.
  const registry = decodeRegistryFile(JSON.parse(await readFile(registryPath, 'utf8')))

  return {
    schemaVersion: registry.schemaVersion,
    registry,
    nixManaged: cachedManaged,
    operatorSecretApps: cachedSecretApps,
  }
}

/** Scheduled jobs and how each is watched — from /export/jobs.json. */
export async function monitoredJobs(): Promise<
  { unit: string; email: boolean; slug: string | null }[]
> {
  const { monitoredJobsList } = await import('./contract/domains/jobs')
  return monitoredJobsList()
}

/** Apps with a tracked operator-secrets file. See `NixManifest.operatorSecretApps`. */
export async function operatorSecretApps(): Promise<string[]> {
  return (await readNixManifest()).operatorSecretApps
}

/** Published hostnames, keyed by webApp name. See `NixManifest.webAppHosts`. */
export async function webAppHosts(): Promise<Record<string, string>> {
  const { publishingFacts } = await import('./contract/domains/publishing')
  const { webApps } = await publishingFacts()
  return Object.fromEntries(Object.entries(webApps).map(([name, w]) => [name, w.hostname]))
}

/** Names pi-hole answers from its own hosts file — from /export/network.json. */
export async function lanHosts(): Promise<{ ip: string; host: string }[]> {
  const { networkFacts } = await import('./contract/domains/network')
  return (await networkFacts()).lanHosts
}

/**
 * Hostnames already published, minus the one this app currently holds — so an
 * app does not collide with itself. From /export/publishing.json.
 */
export async function hostnamesTakenBy(others: string): Promise<string[]> {
  const { publishingFacts } = await import('./contract/domains/publishing')
  return (await publishingFacts()).takenHostnames.filter((h) => h !== others)
}

export async function manifestEntries(): Promise<ManifestEntry[]> {
  const m = await readNixManifest()
  const hasSecrets = new Set(m.operatorSecretApps)
  return [
    ...Object.entries(m.registry.apps).map(([name, a]) => ({ ...a, name, managedInNix: false })),
    ...Object.entries(m.nixManaged).map(([name, a]) => ({ ...a, name, managedInNix: true })),
  ]
    .map((e) => ({ ...e, operatorSecrets: hasSecrets.has(e.name) }))
    .sort((a, b) => a.name.localeCompare(b.name))
}
