import { readFile } from 'node:fs/promises'
import {
  arrayOf,
  bool,
  type Decoder,
  decode,
  int,
  literal,
  nullable,
  num,
  obj,
  optional,
  recordOf,
  str,
} from '../lib/contract/decode'
import { REGISTRY_SCHEMA_VERSION } from '../lib/contract/version'
import { APP_STAGES, type AppStage } from '../lib/stage'
// The one number, in the module the editor can also load: a component may not
// import from host/, and the default a form fills in has to be the default the
// decoder applies.
import { DEFAULT_TASK_TIMEOUT_SEC } from '../lib/tasks'
import { env } from './env'

// What Nix last built, as handed to this container by
// nix/stacks/daedalus/daedalus.nix — two files, read by `readNixManifest`:
// what only nix knows (/export/apps.json: the hand-declared entries and which
// apps have operator secrets — host/contract/domains/apps.ts) and the applied
// registry (NIX_REGISTRY_PATH, /export/applied.json).
//
// This is NOT a second source of truth — it is the *comparison* target. The
// database is authoritative for everything the UI edits; these files are what
// the running system was actually built from. Where they differ, the app has
// pending changes that no Apply has shipped yet, and the UI says so rather
// than pretending the DB is live.

// The ladder itself lives in lib/stage.ts, which the browser can also load.
// Re-exported here because this module is where the registry's shape is
// written down, and a decoder's neighbours are where callers look for it.
export type { AppStage }

export type ManifestEnvVar = { key: string; value: string; note?: string | null }

/**
 * cgroup v2 caps. null on any field = uncapped, which is the platform default
 * — see the `resources` option in nix/platform/apps-options.nix for what each one
 * actually enforces and where the flag names lie about it.
 */
type ManifestResources = {
  cpus: number | null
  memoryMb: number | null
  pids: number | null
}

const NO_RESOURCES: ManifestResources = { cpus: null, memoryMb: null, pids: null }

/**
 * One scheduled task: a systemd timer + service pair named
 * `app-<name>-task-<id>`, generated by nix/modules/apps/apps.nix from this entry.
 *
 * `schedule` is a CONCRETE `OnCalendar` string, never a bare `hourly`/`daily`
 * — the app expands the presets before writing apps.json (lib/tasks.ts), so
 * nix does no arithmetic and the UI can name the exact minute a task runs.
 * `command` is argv, run as `podman exec app-<name> <argv>` with no shell in
 * between, so no value in it has anything to escape out of.
 */
export type ManifestTask = {
  id: string
  schedule: string
  command: string[]
  timeoutSec: number
}

export type ManifestApp = {
  stage: AppStage
  sourceMode?: 'registry' | 'local'
  postgres: boolean
  storage: boolean
  litellm: boolean
  prometheus: boolean
  /** null = `<name>.<baseDomain>`. Exactly one label under it — asserted in nix/modules/apps/apps.nix. */
  hostname?: string | null
  /**
   * The freeze switch. Absent (hand-written entries like daedalus's
   * self.json) = the platform default: nix's `deploy.enable` option
   * (nix/platform/apps-options.nix) defaults to `!source.dev`, which
   * lib/apps/manifest-map.ts approximates as `sourceMode === 'registry'`.
   */
  deploy?: { enable: boolean } | null
  image: string | null
  egress: { container: string; hostPort: number } | null
  env: ManifestEnvVar[]
  auth: {
    mode: 'none' | 'proxy' | 'native'
    healthPath?: string | null
    isolated?: boolean
    allowedGroups?: string[] | null
    bypassRule?: string | null
  }
  presentation: { description: string }
  /** Optional so an apps.json predating the field still parses. */
  resources?: ManifestResources
  /** Same rule as `resources`: absent in a file written before tasks existed. */
  tasks?: ManifestTask[]
  notes?: Record<string, string>
}

// The manifest is the app-registry contract only. The publish/network/jobs
// accessors at the bottom of this file delegate to the /export domains
// (host/contract/domains/).
export type NixManifest = {
  schemaVersion: number
  registry: { schemaVersion: number; apps: Record<string, ManifestApp> }
  nixManaged: Record<string, ManifestApp>
  /**
   * Apps with a tracked `site/vault/apps/<name>-env.sops` — what Nix found,
   * never what daedalus decides (host/contract/domains/apps.ts).
   */
  operatorSecretApps: string[]
}

/**
 * Every app Nix knows about, tagged with whether daedalus may edit it.
 *
 * `operatorSecrets` is resolved here from `operatorSecretApps` so callers see
 * one shape per app instead of having to remember which facts live in which
 * half of the manifest.
 */
export type ManifestEntry = ManifestApp & {
  name: string
  managedInNix: boolean
  operatorSecrets: boolean
}

// The runtime shape of one registry entry. Optional keys decode to the same
// normalised defaults every consumer already applied by hand (`?? null`,
// `?? {}`), so a file from an older writer parses and a malformed one names
// its broken path instead of surfacing as a crash three renders later.
const ns = optional(nullable(str), null)
const nn = optional(nullable(num), null)

export const manifestApp: Decoder<ManifestApp> = obj({
  // From the tuple, so a rung added to the ladder is decodable here without a
  // second edit — and a file Nix accepts can never fail to parse here.
  stage: literal(...APP_STAGES),
  sourceMode: optional(literal('registry', 'local'), 'registry'),
  postgres: bool,
  storage: bool,
  litellm: bool,
  prometheus: bool,
  hostname: ns,
  deploy: optional(nullable(obj({ enable: bool })), null),
  image: ns,
  egress: optional(nullable(obj({ container: str, hostPort: num })), null),
  env: optional(arrayOf(obj({ key: str, value: str, note: ns })), []),
  auth: obj({
    mode: literal('none', 'proxy', 'native'),
    healthPath: ns,
    isolated: optional(bool, false),
    allowedGroups: optional(nullable(arrayOf(str)), null),
    bypassRule: ns,
  }),
  presentation: obj({ description: str }),
  resources: optional(obj({ cpus: nn, memoryMb: nn, pids: nn }), NO_RESOURCES),
  // Added the way `resources` was — `optional` here, `a.tasks or [ ]` in nix —
  // so an apps.json written before the field existed still parses and no
  // schemaVersion bump is owed. A bump is for a breaking reshape.
  //
  // `int` rather than `num` for the timeout: it becomes TimeoutStartSec on a
  // generated unit, and a fractional one is a file systemd would reject after
  // the Apply has already committed.
  tasks: optional(
    arrayOf(
      obj({
        id: str,
        schedule: str,
        command: arrayOf(str),
        timeoutSec: optional(int, DEFAULT_TASK_TIMEOUT_SEC),
      }),
    ),
    [],
  ),
  notes: optional(recordOf(str), {}),
})

const registryFileShape = obj({
  schemaVersion: optional(num, 1),
  apps: recordOf(manifestApp),
})

/**
 * The committed registry (site/apps.json) as parsed JSON, decoded and held
 * to the one schema version this reader understands: the assertion in
 * nix/modules/apps/declarations.nix guards the rebuild; this guards the drift
 * comparison. Exported for
 * the example host's site-files test (host/contract/site-files.test.ts), which is the
 * only other reader — a sample that decodes but is the wrong version must
 * fail exactly the way the box's own file would.
 */
export function decodeRegistryFile(raw: unknown): NixManifest['registry'] {
  const registry = decode(registryFileShape, raw)
  if (registry.schemaVersion !== REGISTRY_SCHEMA_VERSION) {
    throw new Error(
      `applied registry declares schemaVersion ${String(registry.schemaVersion)}; this reader understands ${String(REGISTRY_SCHEMA_VERSION)}`,
    )
  }
  return registry
}

// TEMPORARY (W5): the store-path manifest /export/apps.json replaces, read only
// while the running generation predates the export. Delete with the
// NIX_MANIFEST_PATH row once the engine switch has landed.
async function legacyNixApps(): Promise<Pick<NixManifest, 'nixManaged' | 'operatorSecretApps'>> {
  const managedPath = env.get('NIX_MANIFEST_PATH')
  if (!managedPath) return { nixManaged: {}, operatorSecretApps: [] }
  return decode(
    obj({ nixManaged: recordOf(manifestApp), operatorSecretApps: optional(arrayOf(str), []) }),
    JSON.parse(await readFile(managedPath, 'utf8')),
  )
}

export async function readNixManifest(): Promise<NixManifest> {
  const registryPath = env.get('NIX_REGISTRY_PATH')
  if (!registryPath) {
    throw new Error(
      'NIX_REGISTRY_PATH is not set. It is injected by stacks/daedalus/daedalus.nix — check the container env.',
    )
  }

  // A malformed export is loud on purpose: this is the app's core contract with
  // nix, and a silently empty answer would drop daedalus itself from the list.
  // A missing one is a publisher that has not run (or a bare checkout), and
  // reads as no nix-declared apps, like every other domain.
  const { nixApps } = await import('./contract/domains/apps')
  const apps = await nixApps()
  if (apps.error !== null) throw new Error(`/export/apps.json: ${apps.error}`)
  // TEMPORARY (W5): becomes `const nix = apps.data` with the fallback gone.
  const nix = apps.available ? apps.data : await legacyNixApps()

  // Neither file is cached. Both live at fixed paths that a rebuild rewrites —
  // which is precisely what lets an Apply update them without restarting this
  // app. Caching would reintroduce the restart by another name: the UI would
  // keep reporting drift against a registry that had already been applied.
  const registry = decodeRegistryFile(JSON.parse(await readFile(registryPath, 'utf8')))

  return {
    schemaVersion: registry.schemaVersion,
    registry,
    nixManaged: nix.nixManaged,
    operatorSecretApps: nix.operatorSecretApps,
  }
}

/** Scheduled jobs and how each is watched — from /export/jobs.json. */
export async function monitoredJobs(): Promise<
  { unit: string; email: boolean; slug: string | null }[]
> {
  const { monitoredJobsList } = await import('./contract/domains/jobs')
  return monitoredJobsList()
}

/** Apps with a tracked operator-secrets file. See `NixManifest.operatorSecretApps`. */
export async function operatorSecretApps(): Promise<string[]> {
  return (await readNixManifest()).operatorSecretApps
}

/** Published hostnames, keyed by webApp name — from /export/publishing.json. */
export async function webAppHosts(): Promise<Record<string, string>> {
  const { publishingFacts } = await import('./contract/domains/publishing')
  const { webApps } = await publishingFacts()
  return Object.fromEntries(Object.entries(webApps).map(([name, w]) => [name, w.hostname]))
}

/** Names pi-hole answers from its own hosts file — from /export/network.json. */
export async function lanHosts(): Promise<{ ip: string; host: string }[]> {
  const { networkFacts } = await import('./contract/domains/network')
  return (await networkFacts()).lanHosts
}

/**
 * Hostnames already published, minus the one this app currently holds — so an
 * app does not collide with itself. From /export/publishing.json.
 */
export async function hostnamesTakenBy(others: string): Promise<string[]> {
  const { publishingFacts } = await import('./contract/domains/publishing')
  return (await publishingFacts()).takenHostnames.filter((h) => h !== others)
}

export async function manifestEntries(): Promise<ManifestEntry[]> {
  const m = await readNixManifest()
  const hasSecrets = new Set(m.operatorSecretApps)
  return [
    ...Object.entries(m.registry.apps).map(([name, a]) => ({ ...a, name, managedInNix: false })),
    ...Object.entries(m.nixManaged).map(([name, a]) => ({ ...a, name, managedInNix: true })),
  ]
    .map((e) => ({ ...e, operatorSecrets: hasSecrets.has(e.name) }))
    .sort((a, b) => a.name.localeCompare(b.name))
}
