import { type Decoder, literal, nullable, obj, optional, str } from '../lib/contract/decode'
import { defineBridge } from './bridge'

// Asking the host to set or remove ONE key in an app's operator-secrets file
// (site/vault/apps/<app>-env.sops).
//
// Modelled on claude-rc-request.ts, which is the smallest complete bridge
// here: one request file, one status file, an agent that OUTLIVES its action,
// so `done` and `failed` are both real terminal states and the ordinary status
// poll covers the whole flow.
//
// WHAT CROSSES, AND WHAT CANNOT. The container seals the value first
// (lib/apps/secrets.ts → core/vault.ts's encrypt-only sops) and sends the
// CIPHERTEXT — a whole sops document for one value, sealed to the same
// recipients as the file it is destined for. Plaintext never reaches the
// bridge directory, not even for the moment between two writes: the apply
// directory sits on a snapshotted dataset, so "briefly" there would mean "in
// every hourly snapshot from now on".
//
// The host decrypts it in memory, merges the one key with `sops set`, and
// commits naming the KEY only. It can do that and the container cannot,
// because the host has the age identity and the container has never had one.
//
// WHY ONE KEY AND NOT A FILE. The container cannot re-emit the file: reading
// the other keys back would need the decryption key it deliberately lacks. A
// whole-file write would therefore mean "replace everything with what I can
// see", which is every other secret gone. One key, merged host-side, is the
// only shape this identity can express — and it happens to be the shape with
// the smallest blast radius anyway.
//
// The selector is an app NAME and a key NAME, never a path. The set of
// writable files is generated by nix from the committed registry
// (SECRET_APPS in nix/stacks/daedalus/verbs-lib.nix), as task-run's RUNNABLE
// allowlist is, so a name taken from this request cannot become a path.

type SecretSetAction = 'set' | 'remove'
type SecretSetState = 'idle' | 'running' | 'done' | 'failed'

export type SecretSetStatus = {
  id: string | null
  /** Which app's file the host last touched — null before any request. */
  app: string | null
  /** The KEY. Safe to render: a name is not a value. */
  key: string | null
  action: SecretSetAction | null
  state: SecretSetState
  /** What the host did, in its words. Names keys, never values. */
  detail: string
  error: string
  /** The short rev of the commit the write produced, or "". */
  commit: string
  startedAt: string | null
  finishedAt: string | null
}

/** The status file the host agent writes; decoding `{}` is the idle status. */
const SECRET_SET_STATUS: Decoder<SecretSetStatus> = obj({
  id: optional(nullable(str), null),
  app: optional(nullable(str), null),
  key: optional(nullable(str), null),
  action: optional(nullable(literal('set', 'remove')), null),
  state: optional(literal('idle', 'running', 'done', 'failed'), 'idle'),
  detail: optional(str, ''),
  error: optional(str, ''),
  commit: optional(str, ''),
  startedAt: optional(nullable(str), null),
  finishedAt: optional(nullable(str), null),
})

const bridge = defineBridge<SecretSetStatus>({
  requestFile: 'secret-set-request.json',
  statusFile: 'secret-set-status.json',
  status: SECRET_SET_STATUS,
})

export async function readSecretSetStatus(): Promise<SecretSetStatus> {
  return bridge.readStatus()
}

/**
 * Publish a set request. `ciphertext` is a sops document, never a value —
 * callers get one from `sealAppSecret` and have no other way to make one.
 */
export async function requestSecretSet(input: {
  actor: string
  app: string
  key: string
  ciphertext: string
}): Promise<string> {
  return bridge.request({
    action: 'set',
    app: input.app,
    key: input.key,
    ciphertext: input.ciphertext,
    actor: input.actor,
  })
}

/** Publish a remove request. Nothing is sealed: there is no value to send. */
export async function requestSecretRemove(input: {
  actor: string
  app: string
  key: string
}): Promise<string> {
  return bridge.request({
    action: 'remove',
    app: input.app,
    key: input.key,
    actor: input.actor,
  })
}
