import type { ControllerClient } from './controller/client'
import { type RootAnswer, runRoot } from './root'

// Asking the host to run one of an app's scheduled tasks NOW, instead of
// waiting for its timer.
//
// The task already exists as a systemd pair generated by
// nix/modules/apps/apps.nix — `app-<name>-task-<id>.timer` firing
// `….service` — so there is nothing to construct here and nothing for this
// container to be trusted with. daedalus asks the root helper's `task-run`
// verb (host/root.ts), which starts that EXISTING service — the unit the timer
// starts, with the same timeout, environment and failure mail — and answers
// when the run has finished. A manual run is therefore indistinguishable from
// a scheduled one, which is the property that makes this button safe to press.
//
// Why the id shape is a security control and not tidiness: the value names a
// unit ROOT starts. The request is validated at the seam (server/registry.ts
// `runTaskNow`, with lib/tasks.ts's `isTaskId`: `^[a-z0-9][a-z0-9-]{0,39}$`)
// and again against the app's declared tasks in lib/apps/tasks.ts, and the
// helper takes only a value from its own list, `<app>-task-<id>` for every
// task unit the box has (nix/stacks/daedalus/daedalus-lib.nix
// `runnableTasks`) — this side is not the only guard, and must not be.

/** The helper waits for the longest task's own timeout; a task's default is 900 s. */
const TASK_WAIT_MS = 24 * 60 * 60 * 1000

export async function requestTaskRun(
  input: { actor: string; app: string; task: string },
  client?: ControllerClient,
): Promise<RootAnswer> {
  console.info(`[task-run] ${input.app} ${input.task}, asked by ${input.actor}`)
  return runRoot('task-run', { task: `${input.app}-task-${input.task}` }, TASK_WAIT_MS, client)
}
