import { type Decoder, literal, nullable, obj, optional, str } from '../lib/contract/decode'
import { defineBridge } from './bridge'

// Asking the host to run one of an app's scheduled tasks NOW, instead of
// waiting for its timer.
//
// The task already exists as a systemd pair generated by stacks/apps —
// `app-<name>-task-<id>.timer` firing `…​.service` — so there is nothing to
// construct here and nothing for this container to be trusted with. daedalus
// drops a request naming an app and a task id; the host's path unit starts
// that EXISTING service, which is the same unit the timer starts, with the
// same timeout, the same environment and the same monitoredJobs mail on
// failure. A manual run is therefore indistinguishable from a scheduled one,
// which is the property that makes this button safe to press.
//
// Why the id shape is a security control and not tidiness: the host derives a
// unit name from what it reads here, and that unit is started by ROOT. The
// request is validated at the seam with lib/tasks.ts's `taskId`
// (`^[a-z0-9][a-z0-9-]{0,39}$`) and again against the app's declared tasks in
// lib/apps/tasks.ts, so nothing but an id this box already generated a unit
// for can reach the file. The host agent checks it a third time — this side of
// the bridge is not the only guard, and must not be the only guard.
//
// Same shape as deploy.ts, one verb, one status file. Modelled on
// claude-rc-request.ts: the agent outlives its action, so `done` and `failed`
// are both real terminal states and the ordinary status poll covers the flow.

type TaskRunState = 'idle' | 'running' | 'done' | 'failed'

export type TaskRunStatus = {
  id: string | null
  /** Which app's task the host last ran — null on a status from before any run. */
  app: string | null
  task: string | null
  state: TaskRunState
  error: string
  startedAt: string | null
  finishedAt: string | null
}

/** The status file the host agent writes; decoding `{}` is the idle status. */
const TASK_RUN_STATUS: Decoder<TaskRunStatus> = obj({
  id: optional(nullable(str), null),
  app: optional(nullable(str), null),
  task: optional(nullable(str), null),
  state: optional(literal('idle', 'running', 'done', 'failed'), 'idle'),
  error: optional(str, ''),
  startedAt: optional(nullable(str), null),
  finishedAt: optional(nullable(str), null),
})

const bridge = defineBridge<TaskRunStatus>({
  requestFile: 'task-run-request.json',
  statusFile: 'task-run-status.json',
  status: TASK_RUN_STATUS,
})

export async function readTaskRunStatus(): Promise<TaskRunStatus> {
  return bridge.readStatus()
}

export async function requestTaskRun(input: {
  actor: string
  app: string
  task: string
}): Promise<string> {
  return bridge.request({ app: input.app, task: input.task, actor: input.actor })
}
