import { useRouter } from '@tanstack/react-router'
import { useId, useState } from 'react'
import { cn } from '../../lib/cn'
import { until, when } from '../../lib/format'
import { errorText } from '../../lib/redact'
import {
  DEFAULT_TASK_TIMEOUT_SEC,
  describeSchedule,
  expandSchedule,
  type SchedulePreset,
  taskCommandError,
  taskIdError,
  taskScheduleError,
  taskTimeoutError,
} from '../../lib/tasks'
import { type AppTabData, fetchTaskRunStatus, runTaskNow, saveApp } from '../../server/registry'
import { Segmented } from '../controls'
import { GrafanaLogs } from '../logs'
import { usePolledStatus } from '../status'
import { Alert, AlertDescription } from '../ui/alert'
import { Badge } from '../ui/badge'
import { Button } from '../ui/button'
import { Field, FieldDescription, FieldError, FieldLabel } from '../ui/field'
import { Input } from '../ui/input'
import {
  type AppRecord,
  BOARD_FOOT,
  CHIP,
  GHOST_BTN,
  LEDE,
  SECTION_HEAD,
  SECTION_HEAD_SMALL,
} from './shared'

type TasksData = Extract<AppTabData, { kind: 'tasks' }>
type TaskRow = TasksData['tasks']['tasks'][number]
/** A task as the registry holds it — what the editor edits and saves back. */
type TaskDraft = AppRecord['tasks'][number]

/**
 * What this app runs on a clock.
 *
 * One card per declared task: what it is, when it runs (in words AND as the
 * raw `OnCalendar` string, because the sentence is a convenience and the
 * string is the contract), what it runs, and how its last run ended. The
 * output is read by unit, not by the app's container — see TaskLogs.
 */
export function Tasks({ app, td }: { app: AppRecord; td: TasksData }) {
  const { tasks, running } = td.tasks
  const router = useRouter()
  const readOnly = app.managedInNix

  // What the form is doing, as one value rather than two booleans that can
  // both be true: nothing, adding, or editing exactly one existing task.
  const [editor, setEditor] = useState<{ kind: 'add' } | { kind: 'edit'; id: string } | null>(null)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  /**
   * Write the WHOLE list back, the way every other edit on this page writes a
   * field: straight to Postgres through `saveApp`, then invalidate so the
   * loader recomputes drift and the Apply bar lights.
   *
   * The whole list rather than one task because `updateApp` replaces the
   * app's task rows wholesale, so a partial send would be a deletion of
   * everything omitted. The refusal from the boundary is shown as it came
   * back: those sentences name the task and the rule, and are the same ones
   * the form shows while you type.
   */
  const write = (next: TaskDraft[]) => {
    setSaving(true)
    setError(null)
    void saveApp({ data: { name: app.name, patch: { tasks: next } } })
      .then(async () => {
        setEditor(null)
        await router.invalidate()
      })
      .catch((e: unknown) => {
        setError(errorText(e))
      })
      .finally(() => {
        setSaving(false)
      })
  }

  const remove = (id: string) => {
    write(app.tasks.filter((t) => t.id !== id))
  }

  const submit = (draft: TaskDraft) => {
    write(
      editor?.kind === 'edit'
        ? app.tasks.map((t) => (t.id === editor.id ? draft : t))
        : [...app.tasks, draft],
    )
  }

  return (
    <>
      <p className={LEDE}>
        Each task is a systemd timer and service pair generated by the platform. It runs as{' '}
        <code>podman exec app-{app.name}</code> with the argv below — no shell, so nothing in an
        argument is interpreted — and a failed run mails, like every other scheduled job on this
        box.
      </p>
      {/* The sentence that keeps this tab honest. Everything below is a
          registry row; the timer is generated from site/apps.json, which only
          an Apply writes. */}
      <p className={cn(LEDE, 'mt-[0.55rem]')}>
        Nothing here exists on the box until the next Apply. Adding, editing or removing a task
        changes this app’s registry entry — the Apply is what writes <code>site/apps.json</code>,
        rebuilds, and creates or removes the units.
      </p>

      {!running && (
        <p className={cn(LEDE, 'text-danger')}>
          {app.name} is declared but not running, so it has no container to run a task inside. Tasks
          can be authored now; the timers exist only once it is promoted.
        </p>
      )}

      {error !== null && (
        <Alert variant="warning" className="mt-[1.1rem] mb-0 text-foreground">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {tasks.length === 0 && editor === null && (
        <EmptyState
          app={app.name}
          readOnly={readOnly}
          onAdd={() => {
            setEditor({ kind: 'add' })
          }}
        />
      )}

      {tasks.length > 0 && (
        <ul className="mt-[1.4rem] mr-0 mb-0 ml-0 flex list-none flex-col gap-[0.8rem] p-0">
          {tasks.map((t) =>
            editor?.kind === 'edit' && editor.id === t.id ? (
              <TaskEditor
                key={t.id}
                app={app.name}
                taken={app.tasks.filter((o) => o.id !== t.id).map((o) => o.id)}
                initial={app.tasks.find((o) => o.id === t.id)}
                busy={saving}
                onSubmit={submit}
                onCancel={() => {
                  setEditor(null)
                }}
              />
            ) : (
              <TaskCard
                key={t.id}
                app={app.name}
                task={t}
                running={running}
                initial={td.runStatus}
                readOnly={readOnly || editor !== null}
                busy={saving}
                onEdit={() => {
                  setEditor({ kind: 'edit', id: t.id })
                }}
                onRemove={() => {
                  remove(t.id)
                }}
              />
            ),
          )}
        </ul>
      )}

      {editor?.kind === 'add' && (
        <ul className="mt-[1.4rem] mr-0 mb-0 ml-0 flex list-none flex-col gap-[0.8rem] p-0">
          <TaskEditor
            app={app.name}
            taken={app.tasks.map((t) => t.id)}
            busy={saving}
            onSubmit={submit}
            onCancel={() => {
              setEditor(null)
            }}
          />
        </ul>
      )}

      {!readOnly && editor === null && tasks.length > 0 && (
        <Button
          type="button"
          variant="outline"
          size="sm"
          className={cn(GHOST_BTN, 'mt-[0.9rem]')}
          disabled={saving}
          onClick={() => {
            setEditor({ kind: 'add' })
          }}
        >
          + Add a task
        </Button>
      )}

      {tasks.length > 0 && (
        <>
          <h2 className={SECTION_HEAD}>
            Output
            <span className={SECTION_HEAD_SMALL}>what the last runs wrote</span>
          </h2>
          <TaskLogs tasks={tasks} />
        </>
      )}
    </>
  )
}

/**
 * The tab an app has never used.
 *
 * It explains the thing before offering the button, because "no tasks" is not
 * a problem to fix — most apps want none — and an operator who has not met the
 * feature cannot tell from an empty list whether it is broken or simply empty.
 */
function EmptyState({
  app,
  readOnly,
  onAdd,
}: {
  app: string
  readOnly: boolean
  onAdd: () => void
}) {
  return (
    <div className="mt-[1.4rem] rounded-lg border border-(--border-soft) border-dashed bg-(--panel) px-[1.05rem] py-[1.1rem]">
      <p className="m-0 max-w-[74ch] text-[0.9rem] text-(--text-muted)">
        {app} runs nothing on a clock. A scheduled task is a command run inside this app’s own
        container on a systemd timer — a nightly digest, an hourly sync, a weekly prune — with its
        output in Loki and a mail if it fails.
      </p>
      {readOnly ? (
        <p className={cn(BOARD_FOOT, 'mt-[0.6rem]')}>
          This app is declared by hand in Nix, so its tasks are written there rather than here.
        </p>
      ) : (
        <Button type="button" size="sm" className="mt-[0.85rem]" onClick={onAdd}>
          Add the first task
        </Button>
      )}
    </div>
  )
}

/**
 * One log panel, with a picker, rather than one panel per task.
 *
 * Each panel is a cross-origin Grafana iframe that boots a whole app to draw
 * one log view, so a page with four tasks would pay for four of them before
 * anybody had asked to read any. The Loki selector is an exact `unit="…"`
 * match — there is no prefix form — so one panel means one chosen task.
 */
function TaskLogs({ tasks }: { tasks: TaskRow[] }) {
  const first = tasks[0] as TaskRow
  const [selected, setSelected] = useState(first.id)
  const shown = tasks.find((t) => t.id === selected) ?? first

  return (
    <>
      {tasks.length > 1 && (
        <div className="mb-[0.7rem] flex flex-wrap gap-[0.4rem]">
          {tasks.map((t) => (
            <Button
              key={t.id}
              type="button"
              variant="outline"
              size="sm"
              className={cn(GHOST_BTN, t.id === shown.id && 'border-primary/45 text-foreground')}
              onClick={() => {
                setSelected(t.id)
              }}
            >
              {t.id}
            </Button>
          ))}
        </div>
      )}
      {/* `.service`, and the `unit` form of LogSource: a task is its own
          systemd unit (`app-<name>-task-<id>.service`), so alloy labels its
          lines with that unit and with no container at all. Asking for
          `container="app-<name>"` here would show the app's own log and
          silently omit every line the task wrote. */}
      <GrafanaLogs source={{ unit: `${shown.unit}.service` }} title={`${shown.id} output`} />
    </>
  )
}

function TaskCard({
  app,
  task,
  running,
  initial,
  readOnly,
  busy,
  onEdit,
  onRemove,
}: {
  app: string
  task: TaskRow
  running: boolean
  initial: TasksData['runStatus']
  readOnly: boolean
  busy: boolean
  onEdit: () => void
  onRemove: () => void
}) {
  // Two clicks to remove, rather than a dialog or a typed name: what is lost
  // is a declaration that can be written again in a minute, but the command
  // itself is only in this row — so the second click is worth asking for and
  // a modal is not.
  const [confirming, setConfirming] = useState(false)

  return (
    <li className="rounded-lg border border-(--border-soft) bg-(--panel) px-[1.05rem] py-[0.85rem]">
      <div className="flex flex-wrap items-center gap-x-[0.85rem] gap-y-[0.4rem]">
        <code className="text-[0.95rem] font-semibold">{task.id}</code>
        <Outcome task={task} />
        <span className="ml-auto flex flex-wrap items-center gap-[0.45rem]">
          <RunNowButton app={app} task={task} running={running} initial={initial} />
          {!readOnly && (
            <>
              <Button
                type="button"
                variant="outline"
                size="sm"
                className={GHOST_BTN}
                disabled={busy}
                onClick={onEdit}
              >
                Edit
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                className={cn(
                  GHOST_BTN,
                  confirming && 'border-danger/50 text-danger hover:text-danger',
                )}
                disabled={busy}
                onBlur={() => {
                  setConfirming(false)
                }}
                onClick={() => {
                  if (confirming) onRemove()
                  else setConfirming(true)
                }}
              >
                {confirming ? 'Remove — sure?' : 'Remove'}
              </Button>
            </>
          )}
        </span>
      </div>

      <p className="mt-[0.5rem] mr-0 mb-0 ml-0 flex flex-wrap items-baseline gap-x-[0.8rem] gap-y-[0.25rem] text-[0.85rem]">
        <span>{task.scheduleText}</span>
        {/* The raw string beside the sentence, always. The sentence is this
            app's reading of it; the string is what systemd was given. */}
        <code className="text-[0.78rem] text-(--dim)">{task.schedule}</code>
      </p>

      {/* argv, joined for reading only — the quotes mark where one argument
          ends, since that is exactly what a shell string would lose. */}
      <p className="mt-[0.45rem] mr-0 mb-0 ml-0 font-mono text-[0.8rem] text-(--text-muted) [overflow-wrap:anywhere]">
        {task.command.map((a) => (/\s/.test(a) ? `"${a}"` : a)).join(' ')}
      </p>

      <div className="mt-[0.5rem] flex flex-wrap gap-[1.1rem] text-[0.78rem] text-(--dim)">
        <span>last run {task.lastRunAt === null ? 'never' : when(task.lastRunAt)}</span>
        <span>
          next{' '}
          {task.nextRunAt === null
            ? 'not scheduled'
            : until((Date.parse(task.nextRunAt) - Date.now()) / 1000)}
        </span>
        <span>timeout {task.timeoutSec}s</span>
        <code>{task.unit}</code>
      </div>

      {task.lastRunAt === null && (
        <p className={BOARD_FOOT}>
          No run recorded. Either the timer has not fired since the last boot, or the Apply that
          generates this unit has not happened yet.
        </p>
      )}
    </li>
  )
}

/**
 * How the last run ended, or an admission that nothing is known.
 *
 * Deliberately silent when there is no run to describe: systemd reports
 * success and exit status 0 for a service that has never started, and a green
 * "success" pill on a task that has never run is the most expensive kind of
 * wrong this page could be.
 */
function Outcome({ task }: { task: TaskRow }) {
  if (task.result === null) {
    return (
      <Badge variant="outline" className={cn(CHIP, 'text-(--text-muted)')}>
        no run yet
      </Badge>
    )
  }
  if (task.result === 'success') {
    return (
      <Badge variant="success" className={CHIP}>
        success
      </Badge>
    )
  }
  return (
    <Badge variant="outline" className={cn(CHIP, 'border-danger/45 text-danger')}>
      {task.result}
      {task.exitStatus === null ? '' : ` · exit ${String(task.exitStatus)}`}
    </Badge>
  )
}

/**
 * Start this task's unit now instead of at its next elapse.
 *
 * The same unit the timer starts, with the same timeout and the same failure
 * mail — so a manual run is indistinguishable from a scheduled one, and this
 * is not a second code path to keep working. Shaped like the Redeploy button
 * on the Overview: the server function only publishes a request, so the
 * progress comes from polling the host's status file (components/status.tsx
 * explains why the claim matters).
 */
function RunNowButton({
  app,
  task,
  running,
  initial,
}: {
  app: string
  task: TaskRow
  running: boolean
  initial: TasksData['runStatus']
}) {
  const router = useRouter()
  const {
    status,
    running: inFlight,
    refusal,
    start,
  } = usePolledStatus({
    initial,
    fetch: () => fetchTaskRunStatus(),
    onSettle: () => {
      // The run moves `lastRunAt` and the outcome, and both come from the
      // loader rather than from the status file.
      void router.invalidate()
    },
  })

  // `status` is one file for the whole bridge, so a run of a DIFFERENT task
  // must not light this card up.
  const mine = status.app === app && status.task === task.id

  return (
    <span className="inline-flex items-center gap-[0.6rem] text-[0.76rem]">
      {refusal !== null && <span className="text-danger">{refusal}</span>}
      {refusal === null && mine && status.state === 'failed' && (
        <span className="text-danger" title={status.error || undefined}>
          last attempt failed
        </span>
      )}
      <Button
        type="button"
        variant="outline"
        size="sm"
        className={GHOST_BTN}
        disabled={inFlight || !running}
        title={running ? undefined : 'the app is declared — there is no container to run this in'}
        onClick={() => {
          start(async () => ({
            ok: true,
            value: (await runTaskNow({ data: { name: app, task: task.id } })).id,
          }))
        }}
      >
        {inFlight && mine ? '▷ running…' : inFlight ? '▷ busy…' : '▷ Run now'}
      </Button>
    </span>
  )
}

/** The input face the app's other editors use (settings.tsx spells the same string inline). */
const INPUT =
  'h-auto rounded-[8px] bg-(--panel-2) px-[0.65rem] py-[0.45rem] md:text-[0.87rem] dark:bg-(--panel-2)'

/** The two presets, plus the escape hatch for a calendar written by hand. */
type ScheduleMode = SchedulePreset | 'custom'

/**
 * One argv element, with a key of its own.
 *
 * Keyed by a counter rather than by index: the boxes are added and removed
 * while being typed in, and React reuses a DOM node whose key did not change —
 * with index keys, deleting argument 2 moves 3's text into 2's box while the
 * cursor is in it.
 */
type Arg = { key: number; value: string }

/** Which preset produced this calendar string, or neither. */
function scheduleModeOf(schedule: string, app: string): ScheduleMode {
  if (schedule === expandSchedule('hourly', app)) return 'hourly'
  if (schedule === expandSchedule('daily', app)) return 'daily'
  return 'custom'
}

/**
 * Add or edit one task.
 *
 * Three decisions here are the feature rather than the form:
 *
 * The presets expand to a CONCRETE OnCalendar before anything is saved
 * (lib/tasks.ts), and the expansion is shown — so the operator reads the exact
 * minute the timer will elapse, on this app's own stable minute, which is
 * never :00. Writing `hourly` through would be accepted by systemd and would
 * fire in myspeed's DNS blackout; the boundary refuses it, and so does nix.
 *
 * The command is argv, entered one argument per box. A single free-text line
 * split on spaces cannot express `["echo", "a b"]`, and the failure is silent:
 * the task runs, with two arguments where one was meant.
 *
 * Every rule shows its sentence as you type, from the same functions the
 * server boundary enforces — so a refusal is visible before the save rather
 * than returned by it.
 */
function TaskEditor({
  app,
  taken,
  initial,
  busy,
  onSubmit,
  onCancel,
}: {
  app: string
  /** The OTHER tasks' ids — what this one may not be called. */
  taken: string[]
  initial?: TaskDraft
  busy: boolean
  onSubmit: (task: TaskDraft) => void
  onCancel: () => void
}) {
  const idField = useId()
  const customField = useId()
  const timeoutField = useId()

  const [id, setId] = useState(initial?.id ?? '')
  const [mode, setMode] = useState<ScheduleMode>(
    initial ? scheduleModeOf(initial.schedule, app) : 'daily',
  )
  const [custom, setCustom] = useState(
    initial && scheduleModeOf(initial.schedule, app) === 'custom' ? initial.schedule : '',
  )
  const [args, setArgs] = useState<Arg[]>(() =>
    (initial?.command ?? ['']).map((value, i) => ({ key: i, value })),
  )
  const [nextKey, setNextKey] = useState(() => (initial?.command.length ?? 1) + 1)
  const [timeoutText, setTimeoutText] = useState(
    String(initial?.timeoutSec ?? DEFAULT_TASK_TIMEOUT_SEC),
  )

  const schedule = mode === 'custom' ? custom.trim() : expandSchedule(mode, app)
  const command = args.map((a) => a.value)
  const timeoutSec = Number(timeoutText)

  const idErr = taskIdError(id, taken)
  const scheduleErr = taskScheduleError(schedule)
  const commandErr = taskCommandError(command)
  const timeoutErr = Number.isNaN(timeoutSec)
    ? 'must be a number of seconds.'
    : taskTimeoutError(timeoutSec)
  const ok = idErr === null && scheduleErr === null && commandErr === null && timeoutErr === null

  // Errors are shown once a field has been WRITTEN in, never on an untouched
  // one: a form that opens with two red lines reads as broken rather than
  // empty. Saving is disabled by `ok` either way, so nothing is hidden that
  // would let a bad task through.
  const commandTouched = args.length > 1 || command.some((a) => a !== '')

  return (
    <li className="rounded-lg border border-primary/40 bg-(--panel) px-[1.05rem] py-[0.95rem]">
      <div className="grid grid-cols-2 gap-x-[1.2rem] gap-y-[0.2rem] max-[46rem]:grid-cols-1">
        <Field className="gap-[0.3rem] py-2">
          <FieldLabel htmlFor={idField} className="text-[0.76rem] font-normal text-(--dim)">
            Id
          </FieldLabel>
          <Input
            id={idField}
            type="text"
            className={INPUT}
            value={id}
            placeholder="digest"
            // An existing task's id is the unit name the box already knows, and
            // renaming it is a delete plus a create rather than an edit — so it
            // is set once, at creation, and read-only afterwards.
            disabled={initial !== undefined}
            aria-invalid={idErr !== null && id !== ''}
            onChange={(e) => {
              setId(e.target.value)
            }}
          />
          {idErr !== null && id !== '' ? (
            <FieldError className="text-[0.76rem] leading-[1.45]">{idErr}</FieldError>
          ) : (
            <FieldDescription className="text-[0.76rem] leading-[1.45]">
              {initial === undefined ? (
                <>
                  Becomes{' '}
                  <code>
                    app-{app}-task-{id || '<id>'}
                  </code>
                  , and cannot be changed afterwards.
                </>
              ) : (
                <>
                  Fixed: this is the unit name{' '}
                  <code>
                    app-{app}-task-{id}
                  </code>
                  . Remove and re-add to rename.
                </>
              )}
            </FieldDescription>
          )}
        </Field>

        <Field className="gap-[0.3rem] py-2">
          <FieldLabel htmlFor={timeoutField} className="text-[0.76rem] font-normal text-(--dim)">
            Timeout
          </FieldLabel>
          <Input
            id={timeoutField}
            type="number"
            min={1}
            step={1}
            className={INPUT}
            value={timeoutText}
            aria-invalid={timeoutErr !== null}
            onChange={(e) => {
              setTimeoutText(e.target.value)
            }}
          />
          {timeoutErr !== null ? (
            <FieldError className="text-[0.76rem] leading-[1.45]">{timeoutErr}</FieldError>
          ) : (
            <FieldDescription className="text-[0.76rem] leading-[1.45]">
              Seconds. <code>TimeoutStartSec</code> on the generated unit: a run still going at{' '}
              {timeoutText}s is killed and mailed as a failure.
            </FieldDescription>
          )}
        </Field>
      </div>

      <Field className="gap-[0.35rem] py-2">
        <FieldLabel className="text-[0.76rem] font-normal text-(--dim)">Schedule</FieldLabel>
        <div>
          <Segmented
            value={mode}
            label="Schedule"
            onChange={(v: ScheduleMode) => {
              setMode(v)
            }}
            options={[
              { value: 'hourly', label: 'Hourly', icon: '↻' },
              { value: 'daily', label: 'Daily', icon: '☾' },
              { value: 'custom', label: 'Custom', icon: '✎' },
            ]}
          />
        </div>
        {mode === 'custom' && (
          <Input
            id={customField}
            type="text"
            className={cn(INPUT, 'mt-[0.35rem] font-mono')}
            value={custom}
            placeholder="Mon *-*-* 03:17:00"
            aria-invalid={scheduleErr !== null && custom !== ''}
            onChange={(e) => {
              setCustom(e.target.value)
            }}
          />
        )}
        {/* The expansion, always, and beside the sentence: the string is what
            systemd is given and the sentence is this app's reading of it. A
            preset that did not show its minute would be a schedule chosen
            blind — and the minute is the whole reason the presets exist. */}
        {scheduleErr !== null && !(mode === 'custom' && custom === '') ? (
          <FieldError className="text-[0.76rem] leading-[1.45]">{scheduleErr}</FieldError>
        ) : (
          <p className="mt-[0.15rem] mr-0 mb-0 ml-0 flex flex-wrap items-baseline gap-x-[0.7rem] text-[0.8rem]">
            <span>{schedule === '' ? 'No schedule yet' : describeSchedule(schedule)}</span>
            <code className="text-[0.78rem] text-(--dim)">{schedule}</code>
          </p>
        )}
        {mode !== 'custom' && (
          <FieldDescription className="text-[0.76rem] leading-[1.45]">
            The minute is derived from this app’s name, so it is stable across edits and never :00 —
            that is when myspeed’s speedtest takes house-wide DNS down for a couple of minutes.
          </FieldDescription>
        )}
      </Field>

      <Field className="gap-[0.35rem] py-2">
        <FieldLabel className="text-[0.76rem] font-normal text-(--dim)">Command (argv)</FieldLabel>
        <ol className="m-0 flex list-none flex-col gap-[0.35rem] p-0">
          {args.map((a, i) => (
            <li key={a.key} className="flex items-center gap-[0.5rem]">
              <span className="w-[1.1rem] shrink-0 text-right text-[0.72rem] text-(--dim)">
                {i + 1}
              </span>
              <Input
                type="text"
                aria-label={`argument ${String(i + 1)}`}
                className={cn(INPUT, 'font-mono')}
                value={a.value}
                placeholder={i === 0 ? 'node' : 'scripts/digest.mjs'}
                onChange={(e) => {
                  const { value } = e.target
                  setArgs((prev) => prev.map((p) => (p.key === a.key ? { ...p, value } : p)))
                }}
              />
              <Button
                type="button"
                variant="outline"
                size="sm"
                className={cn(GHOST_BTN, 'shrink-0')}
                aria-label={`remove argument ${String(i + 1)}`}
                disabled={args.length === 1}
                onClick={() => {
                  setArgs((prev) => prev.filter((p) => p.key !== a.key))
                }}
              >
                ✕
              </Button>
            </li>
          ))}
        </ol>
        <div>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className={cn(GHOST_BTN, 'mt-[0.15rem]')}
            onClick={() => {
              setArgs((prev) => [...prev, { key: nextKey, value: '' }])
              setNextKey((k) => k + 1)
            }}
          >
            + Argument
          </Button>
        </div>
        {commandErr !== null && commandTouched ? (
          <FieldError className="text-[0.76rem] leading-[1.45]">{commandErr}</FieldError>
        ) : (
          <FieldDescription className="text-[0.76rem] leading-[1.45]">
            One argument per box, passed through exactly as typed — no shell, so nothing is split on
            spaces and nothing in an argument is interpreted. Runs as:{' '}
            <code className="[overflow-wrap:anywhere]">
              podman exec app-{app} {command.map((c) => (/\s/.test(c) ? `"${c}"` : c)).join(' ')}
            </code>
          </FieldDescription>
        )}
      </Field>

      <div className="mt-[0.7rem] flex flex-wrap items-center gap-[0.6rem]">
        <Button
          type="button"
          size="sm"
          disabled={!ok || busy}
          onClick={() => {
            onSubmit({ id: id.trim().toLowerCase(), schedule, command, timeoutSec })
          }}
        >
          {busy ? 'Saving…' : initial === undefined ? 'Add task' : 'Save task'}
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          className={GHOST_BTN}
          disabled={busy}
          onClick={onCancel}
        >
          Cancel
        </Button>
        <span className="text-[0.73rem] text-(--dim)">
          Saved to the registry; the unit appears on the next Apply.
        </span>
      </div>
    </li>
  )
}
