# Set or remove ONE key in an app's operator-secrets file, on request from
# daedalus: the root helper's `secret-set` (daedalus-verbs.nix), started as
# `daedalus-secret-set@<run id>` as the operator, with the request as its
# `request` credential (host/lib.sh take_request) — the app, the action, the
# key and the actor as selectors, the sealed value as the payload — and the
# host's SSH key as its `hostkey` credential, the one thing it needs root's
# files for.
#
# The host half of the write-only secrets editor. daedalus holds an
# encrypt-only sops identity — a static sops binary and the PUBLIC recipients
# in $SITE_DIR/.sops.yaml, no age key anywhere (the image's Dockerfile, sops stage)
# — so it can seal a value and can never open one. Everything that needs the
# decryption key happens here:
#
#   1. open the sealed value the request carries, in memory;
#   2. merge it into site/vault/apps/<app>-env.sops with `sops set`, which
#      leaves every OTHER key in that file byte-identical;
#   3. commit, naming the key and never the value.
#
# Merging host-side is not an optimisation, it is the only shape this
# arrangement can take. A container that cannot read the file cannot re-emit
# it, so "write the whole file" would mean "replace it with the one key I can
# see" — every other secret gone.
#
# ── what is trusted, and what is not ──────────────────────────────────────
#
# $SECRET_APPS is generated by nix from the committed registry (site/apps.json)
# into this script's wrapper, as VAULT_APP_SECRETS is for apply.sh, and is the
# same list the helper holds the `app` selector to. The request supplies an app
# NAME, never a path; the path is built here from a name that matched that
# list. An app this box has not applied therefore has no writable file at all.
#
# The KEY is checked against the environment-variable charset before it reaches
# `sops set`, where it becomes a document index. daedalus checks the same thing
# twice before this (lib/apps/secret-keys.ts, and again at the server
# function), and the helper holds it to the verb's `key` pattern; this is the
# check that has to hold, because it is the last one before `sops set`.
#
# ── what never touches a disk ─────────────────────────────────────────────
#
# The plaintext exists only inside the `sops decrypt | jq | sops set` pipeline
# — no temp file, no argv (that is what `--value-stdin` is for), no journal
# line. The container seals the value before the request exists, so what
# crosses the controller, the helper and the run file (tmpfs, root's 0600; this
# unit's credential) is ciphertext only.
#
# ── what this does NOT do ─────────────────────────────────────────────────
#
# It does not rebuild: the write is a committed file, and turning it into
# running state is the Apply's job, which has its own agent, its own lock and
# its own rollback. The page says so.

set -euo pipefail

# The helper's split: a request this agent correctly REFUSES exits 0 with a
# last line `refused: <reason>`, which the helper answers as `refused` and the
# page shows. Only the agent being unable to do its job exits 1 and leaves a
# failed unit for `systemctl --failed`.
refuse() {
  echo "refused: $1"
  exit 0
}

fail() {
  echo "secret-set agent failure: $1" >&2
  exit 1
}

# sops with the host's identity, standing in the site directory.
#
# The identity is derived from the SSH host key by ssh-to-age through
# SOPS_AGE_KEY_CMD, so it lives in a pipe for the length of one call and is
# never written to a file or an environment variable — sops-nix derives the
# same identity the same way at activation, which is why this box's own
# recipient in .sops.yaml matches it. The key is the unit's `hostkey`
# credential: systemd reads it as root and hands this operator-run unit a
# private read-only copy. HOME is an empty private directory, so sops finds
# no other identity (the operator's own SSH key, an age keys.txt) to try.
#
# The cwd is what makes `--filename-override vault/apps/…` match .sops.yaml's
# creation rule: sops resolves that regex against the path RELATIVE to where it
# stands. --config names the file explicitly so the walk-up never finds
# another.
sops_host() {
  (
    cd "$SITE_DIR" &&
      SOPS_AGE_KEY_CMD="$SSH_TO_AGE -private-key -i $CREDENTIALS_DIRECTORY/hostkey" HOME="$SOPS_HOME" \
        "$SOPS" --config "$SITE_DIR/.sops.yaml" "$@"
  )
}

# Temps in the unit's private /tmp (PrivateTmp): nothing else can reach them.
# The request (its payload is the sealed value) is kept in one rather than in
# a variable, so it never reaches a command line.
REQ="$(mktemp)"
WORK="$(mktemp)"
SEALED="$(mktemp)"
SOPS_HOME="$(mktemp -d)"
trap 'rm -rf "$REQ" "$WORK" "$SEALED" "$SOPS_HOME"' EXIT

[ -r "${CREDENTIALS_DIRECTORY:-}/hostkey" ] || fail "no hostkey credential: this unit is started by the root helper"
take_request >"$REQ" || exit 1

APP="$(jq -r '.selectors.app // ""' "$REQ")"
KEY="$(jq -r '.selectors.key // ""' "$REQ")"
ACTION="$(jq -r '.selectors.action // ""' "$REQ")"
ACTOR="$(jq -r '.selectors.actor // "daedalus"' "$REQ")"

case "$ACTION" in
set | remove) ;;
*) refuse "unknown action '$ACTION'" ;;
esac

# The allowlist. Matching the whole token is what stops a name that merely
# CONTAINS an app's name from passing.
case " $SECRET_APPS " in
*" $APP "*) ;;
*) refuse "no app named '$APP' in the applied registry, so this box has no secrets file for it" ;;
esac

# The key charset, as the wall in front of `sops set`'s index argument. A name
# that is not [A-Za-z_][A-Za-z0-9_]* is not an environment variable, and the
# rest of this script may treat $KEY as a literal because of these four lines.
case "$KEY" in
'') refuse "the request names no key" ;;
[!A-Za-z_]*) refuse "'$KEY' is not an environment variable name" ;;
*[!A-Za-z0-9_]*) refuse "'$KEY' is not an environment variable name" ;;
# sops keeps its own rows in a dotenv file under this prefix (sops_mac,
# sops_version, sops_age__list_0__map_enc). Setting one would corrupt the
# file's metadata rather than add a secret.
sops_*) refuse "'$KEY' is reserved for sops's own metadata" ;;
esac
[ "${#KEY}" -le 64 ] || refuse "'$KEY' is longer than 64 characters"

# The payload: a set carries the sealed value, a remove carries none.
jq -j '.payload // ""' "$REQ" >"$SEALED"
if [ "$ACTION" = set ]; then
  [ -s "$SEALED" ] || refuse "the request carries no sealed value"
  # A sops document, not something else that happens to be JSON. The app checks
  # its own sops output before sending (core/vault.ts ciphertextError); this is
  # the same question asked on the far side of the helper.
  jq -e 'type == "object" and (.data | type) == "string" and (.sops | type) == "object"' \
    "$SEALED" >/dev/null 2>&1 ||
    refuse "the sealed value is not a sops document"
else
  [ ! -s "$SEALED" ] || refuse "a remove carries no value, and this one carries one"
fi

FILE="vault/apps/$APP-env.sops"

echo "reading $FILE"

if [ -f "$SITE_DIR/$FILE" ]; then
  read_as_operator "$SITE_DIR/$FILE" >"$WORK" ||
    fail "could not read $FILE as $OPERATOR_USER (see the journal)"
  [ -s "$WORK" ] || refuse "$FILE is empty, so it is not a sops file — nothing was changed"
elif [ "$ACTION" = remove ]; then
  refuse "$APP has no secrets file, so there is no $KEY to remove"
else
  # The first key for this app. An empty dotenv, encrypted into place: sops
  # writes the recipients and the MAC, and the `set` below adds the key. This
  # is also what turns operator-secrets-lib.nix's switch ON for the app — the
  # file existing IS the setting — so the next rebuild starts injecting it.
  sops_host encrypt --input-type dotenv --output-type dotenv \
    --filename-override "$FILE" /dev/null >"$WORK" ||
    fail "sops could not create $FILE"
fi

if [ "$ACTION" = remove ]; then
  # Refused rather than committed as a no-op: `sops unset --idempotent` would
  # happily rewrite the file (new MAC, new timestamp) and leave a commit
  # claiming a removal that removed nothing.
  grep -q -- "^$KEY=" "$WORK" || refuse "$FILE has no $KEY, so nothing was removed"
  sops_host unset --input-type dotenv --output-type dotenv "$WORK" "[\"$KEY\"]" ||
    fail "sops could not remove $KEY from $FILE"
else
  # The one pipeline the plaintext lives in. `--value-stdin` keeps it out of
  # the process table; `jq -Rs` is there because `sops set` takes its value as
  # JSON, and encoding it any other way would mean a shell quoting it.
  if ! sops_host decrypt --input-type binary --output-type binary "$SEALED" |
    jq -Rs . |
    sops_host set --value-stdin --input-type dotenv --output-type dotenv "$WORK" "[\"$KEY\"]"; then
    fail "sops could not seal $KEY into $FILE — is the host still a recipient of it?"
  fi
fi

# --- publish into the site directory --------------------------------------
# Everything from here is host/site-lib.sh's, and runs as the operator: the
# site directory is theirs, inside their repository, and root writing a file
# there by name is the rule lib.sh exists to keep.
echo "writing $FILE"

site_backup "$FILE" ||
  fail "could not keep the previous bytes of $FILE, so it was not written (see the journal)"
if ! site_put "$FILE" "$WORK"; then
  site_restore "$FILE"
  fail "could not write $FILE into $SITE_DIR as $OPERATOR_USER (see the journal)"
fi

# --- stage and commit ------------------------------------------------------
# Not optional here, unlike an Apply. This file is read by nix, a flake
# sees only tracked files, and the value it holds cannot be typed again from
# anywhere — an uncommitted rewrite of it is the one change on this box that
# is unrecoverable. So it is always staged and always committed.
echo "committing"
site_stage "$FILE" || fail "git add failed for $FILE"
COMMIT="$(site_commit "secrets: $APP $ACTION $KEY" "$ACTOR")" || fail "git commit failed"

# The repository facts, where the page reads "set <when> by <who>" from (the
# git history of this file IS the audit trail), refresh when this unit is done:
# its ExecStartPost starts the repo snapshot as root (daedalus-verbs.nix), a
# thing the operator this runs as may not ask systemd for.

if [ "$ACTION" = set ]; then
  DETAIL="sealed $KEY into $FILE"
else
  DETAIL="removed $KEY from $FILE"
fi
[ -z "$COMMIT" ] || DETAIL="$DETAIL, committed $COMMIT"
DETAIL="$DETAIL — the container reads it on the next Apply"
echo "$DETAIL"
