# Set or remove ONE key in an app's operator-secrets file, on request from
# daedalus.
#
# The host half of the write-only secrets editor. daedalus holds an
# encrypt-only sops identity — a static sops binary and the PUBLIC recipients
# in $SITE_DIR/.sops.yaml, no age key anywhere (the image's Dockerfile, sops stage)
# — so it can seal a value and can never open one. Everything that needs the
# decryption key happens here:
#
#   1. open the sealed value the request carries, in memory;
#   2. merge it into site/vault/apps/<app>-env.sops with `sops set`, which
#      leaves every OTHER key in that file byte-identical;
#   3. commit, naming the key and never the value.
#
# Merging host-side is not an optimisation, it is the only shape this
# arrangement can take. A container that cannot read the file cannot re-emit
# it, so "write the whole file" would mean "replace it with the one key I can
# see" — every other secret gone.
#
# ── what is trusted, and what is not ──────────────────────────────────────
#
# $SECRET_APPS is generated by nix from the committed registry (site/apps.json)
# into this script's wrapper, exactly as $RUNNABLE is for task-run.sh and
# VAULT_APP_SECRETS is for apply.sh. The request supplies an app NAME, never a
# path; the path is built here from a name that matched that list. An app this
# box has not applied therefore has no writable file at all.
#
# The KEY is checked against the environment-variable charset before it reaches
# `sops set`, where it becomes a document index. daedalus checks the same thing
# twice before this (lib/apps/secret-keys.ts, and again at the server
# function); this is the check that has to hold, because it is the only one on
# this side of the trust boundary.
#
# ── what never touches a disk ─────────────────────────────────────────────
#
# The plaintext exists only inside the `sops decrypt | jq | sops set` pipeline
# — no temp file, no argv (that is what `--value-stdin` is for), no journal
# line. $APPLY_DIR sits on a snapshotted dataset, so a plaintext written there
# "briefly" would be in every hourly snapshot from then on; that is why the
# container seals the value before the request exists rather than letting this
# agent do the encrypting.
#
# ── what this does NOT do ─────────────────────────────────────────────────
#
# It does not rebuild. Same reasoning as host/site-write.sh: the write is a
# committed file, and turning it into running state is the Apply's job, which
# has its own agent, its own lock and its own rollback. The page says so.

set -euo pipefail

REQ="$APPLY_DIR/secret-set-request.json"
STATUS="$APPLY_DIR/secret-set-status.json"

APP=""
KEY=""
ACTION=""
COMMIT=""

write_status() {
  write_json_atomic "$STATUS" <<EOF
{"id":"$REQ_ID","app":$(jq -Rn --arg a "$APP" '$a'),"key":$(jq -Rn --arg k "$KEY" '$k'),"action":$(jq -Rn --arg c "$ACTION" '$c'),"state":"$1","detail":$(jq -Rn --arg d "${2-}" '$d'),"error":$(jq -Rn --arg e "${3-}" '$e'),"commit":$(jq -Rn --arg r "$COMMIT" '$r'),"startedAt":"$STARTED_AT","finishedAt":"$(date -Is)"}
EOF
}

# Same split as host/task-run.sh: a request this agent correctly REFUSES exits
# 0 — the agent worked, and the refusal is rendered on the page that asked.
# Only the agent being unable to do its job exits 1 and leaves a failed unit
# for `systemctl --failed`.
reject() {
  write_status failed "" "$1"
  echo "secret-set request rejected: $1" >&2
  exit 0
}

fail() {
  write_status failed "" "$1"
  echo "secret-set agent failure: $1" >&2
  exit 1
}

# sops as root, standing in the site directory.
#
# The identity is derived from the SSH host key by ssh-to-age through
# SOPS_AGE_KEY_CMD, so it lives in a pipe for the length of one call and is
# never written to a file or an environment variable — sops-nix derives the
# same identity the same way at activation, which is why this box's own
# recipient in .sops.yaml matches it.
#
# The cwd is what makes `--filename-override vault/apps/…` match .sops.yaml's
# creation rule: sops resolves that regex against the path RELATIVE to where it
# stands. --config names the file explicitly so the walk-up never finds
# another.
sops_root() {
  (
    cd "$SITE_DIR" &&
      SOPS_AGE_KEY_CMD="$SSH_TO_AGE -private-key -i $HOST_SSH_KEY" HOME=/root \
        "$SOPS" --config "$SITE_DIR/.sops.yaml" "$@"
  )
}

[ -f "$REQ" ] || exit 0

# Read once, as the operator, never through a link (host/lib.sh); a symlinked
# request is refused with a failed unit — the app never writes one.
REQ_JSON="$(read_request "$REQ")" || exit 1

REQ_ID="$(jq -r '.id // ""' <<<"$REQ_JSON")"
[ -n "$REQ_ID" ] || exit 0
case "$REQ_ID" in
*[!0-9a-fA-F-]*) exit 0 ;;
esac
STARTED_AT="$(date -Is)"

# Replay guard, same as every bridge: the path unit re-fires on a
# daemon-reload replay at boot, and without this every reboot would re-apply
# the last secret anybody set — over whatever has been set since.
if [ -f "$STATUS" ] && [ "$(published_id "$STATUS")" = "$REQ_ID" ]; then
  exit 0
fi

APP="$(jq -r '.app // ""' <<<"$REQ_JSON")"
KEY="$(jq -r '.key // ""' <<<"$REQ_JSON")"
ACTION="$(jq -r '.action // ""' <<<"$REQ_JSON")"
ACTOR="$(jq -r '.actor // "daedalus"' <<<"$REQ_JSON")"

case "$ACTION" in
set | remove) ;;
*) reject "unknown action '$ACTION'" ;;
esac

# The allowlist. Matching the whole token is what stops a name that merely
# CONTAINS an app's name from passing.
case " $SECRET_APPS " in
*" $APP "*) ;;
*) reject "no app named '$APP' in the applied registry, so this box has no secrets file for it" ;;
esac

# The key charset, as the wall in front of `sops set`'s index argument. A name
# that is not [A-Za-z_][A-Za-z0-9_]* is not an environment variable, and the
# rest of this script may treat $KEY as a literal because of these four lines.
case "$KEY" in
'') reject "the request names no key" ;;
[!A-Za-z_]*) reject "'$KEY' is not an environment variable name" ;;
*[!A-Za-z0-9_]*) reject "'$KEY' is not an environment variable name" ;;
# sops keeps its own rows in a dotenv file under this prefix (sops_mac,
# sops_version, sops_age__list_0__map_enc). Setting one would corrupt the
# file's metadata rather than add a secret.
sops_*) reject "'$KEY' is reserved for sops's own metadata" ;;
esac
[ "${#KEY}" -le 64 ] || reject "'$KEY' is longer than 64 characters"

FILE="vault/apps/$APP-env.sops"

write_status running "reading $FILE" ""

# Root-private temps in root's own /tmp: the container cannot reach them, so
# these are the one place in this script where root may work by name.
WORK="$(mktemp)"
SEALED="$(mktemp)"
trap 'rm -f "$WORK" "$SEALED"' EXIT

if [ -f "$SITE_DIR/$FILE" ]; then
  read_as_operator "$SITE_DIR/$FILE" >"$WORK" ||
    fail "could not read $FILE as $OPERATOR_USER (see the journal)"
  [ -s "$WORK" ] || reject "$FILE is empty, so it is not a sops file — nothing was changed"
elif [ "$ACTION" = remove ]; then
  reject "$APP has no secrets file, so there is no $KEY to remove"
else
  # The first key for this app. An empty dotenv, encrypted into place: sops
  # writes the recipients and the MAC, and the `set` below adds the key. This
  # is also what turns operator-secrets-lib.nix's switch ON for the app — the
  # file existing IS the setting — so the next rebuild starts injecting it.
  sops_root encrypt --input-type dotenv --output-type dotenv \
    --filename-override "$FILE" /dev/null >"$WORK" ||
    fail "sops could not create $FILE"
fi

if [ "$ACTION" = remove ]; then
  # Refused rather than committed as a no-op: `sops unset --idempotent` would
  # happily rewrite the file (new MAC, new timestamp) and leave a commit
  # claiming a removal that removed nothing.
  grep -q -- "^$KEY=" "$WORK" || reject "$FILE has no $KEY, so nothing was removed"
  sops_root unset --input-type dotenv --output-type dotenv "$WORK" "[\"$KEY\"]" ||
    fail "sops could not remove $KEY from $FILE"
else
  jq -j '.ciphertext // ""' <<<"$REQ_JSON" >"$SEALED"
  [ -s "$SEALED" ] || reject "the request carries no sealed value"
  # A sops document, not something else that happens to be JSON. The app checks
  # its own sops output before sending (core/vault.ts ciphertextError); this is
  # the same question asked on the far side of the bridge.
  jq -e 'type == "object" and (.data | type) == "string" and (.sops | type) == "object"' \
    "$SEALED" >/dev/null 2>&1 ||
    reject "the sealed value is not a sops document"

  # The one pipeline the plaintext lives in. `--value-stdin` keeps it out of
  # the process table; `jq -Rs` is there because `sops set` takes its value as
  # JSON, and encoding it any other way would mean a shell quoting it.
  if ! sops_root decrypt --input-type binary --output-type binary "$SEALED" |
    jq -Rs . |
    sops_root set --value-stdin --input-type dotenv --output-type dotenv "$WORK" "[\"$KEY\"]"; then
    fail "sops could not seal $KEY into $FILE — is the host still a recipient of it?"
  fi
fi

# --- publish into the site directory --------------------------------------
# Everything from here is host/site-lib.sh's, and runs as the operator: the
# site directory is theirs, inside their repository, and root writing a file
# there by name is the rule lib.sh exists to keep.
write_status running "writing $FILE" ""

site_backup "$FILE" ||
  fail "could not keep the previous bytes of $FILE, so it was not written (see the journal)"
if ! site_put "$FILE" "$WORK"; then
  site_restore "$FILE"
  fail "could not write $FILE into $SITE_DIR as $OPERATOR_USER (see the journal)"
fi

# --- stage and commit ------------------------------------------------------
# Not optional here, unlike a site write. This file is read by nix, a flake
# sees only tracked files, and the value it holds cannot be typed again from
# anywhere — an uncommitted rewrite of it is the one change on this box that
# is unrecoverable. So it is always staged and always committed.
write_status running "committing" ""
site_stage "$FILE" || fail "git add failed for $FILE"
COMMIT="$(site_commit "secrets: $APP $ACTION $KEY" "$ACTOR")" || fail "git commit failed"

# Refresh the repository facts, which is where the page reads "set <when> by
# <who>" from — the git history of this file IS the audit trail.
"$SYSTEMCTL" start daedalus-repo-snapshot.service || true

if [ "$ACTION" = set ]; then
  DETAIL="sealed $KEY into $FILE"
else
  DETAIL="removed $KEY from $FILE"
fi
[ -z "$COMMIT" ] || DETAIL="$DETAIL, committed $COMMIT"
DETAIL="$DETAIL — the container reads it on the next Apply"
write_status "done" "$DETAIL" ""
echo "secret-set: $DETAIL"
