# Run one of an app's scheduled tasks NOW, on request from daedalus.
#
# This runs nothing itself. `app-<app>-task-<id>.service` (generated by
# modules/apps/apps.nix from the registry's `tasks`) already knows the argv,
# the container, the timeout and how to reach rootless podman, and its failure
# already mails through fleet.monitoredJobs. Reimplementing any of that here
# would be a second answer to "what does this task do" — and the wrong one the
# first time a task's command changed.
#
# So the whole job is: validate the app/task pair, start that unit, wait,
# report. The wait is the point: `systemctl start` without it returns as soon
# as the job is enqueued, which the page would render as a successful run
# while the task was still going (or already failing).
#
# Runs as root because starting a system unit needs it. The container cannot,
# which is the entire reason this file exists — daedalus writes a request into
# a bind mount and a systemd.path unit runs this.

set -euo pipefail

REQ="$APPLY_DIR/task-run-request.json"
STATUS="$APPLY_DIR/task-run-status.json"

APP=""
TASK=""

write_status() {
  write_json_atomic "$STATUS" <<EOF
{"id":"$REQ_ID","app":$(jq -Rn --arg a "$APP" '$a'),"task":$(jq -Rn --arg t "$TASK" '$t'),"state":"$1","error":$(jq -Rn --arg e "${2-}" '$e'),"startedAt":"$STARTED_AT","finishedAt":"$(date -Is)"}
EOF
}

# Same split as host/claude-rc.sh: a request this agent correctly REFUSES
# exits 0 — the agent worked, and the refusal is shown on the page that asked.
# Only the agent being unable to do its job exits 1 and leaves a failed unit
# for `systemctl --failed`.
reject() {
  write_status failed "$1"
  echo "task-run request rejected: $1" >&2
  exit 0
}

[ -f "$REQ" ] || exit 0

# Read once, as the operator, never through a link (host/lib.sh); a symlinked
# request is refused with a failed unit — the app never writes one.
REQ_JSON="$(read_request "$REQ")" || exit 1

REQ_ID="$(jq -r '.id // ""' <<<"$REQ_JSON")"
[ -n "$REQ_ID" ] || exit 0
STARTED_AT="$(date -Is)"

# Replay guard, same as every bridge: the path unit re-fires on a
# daemon-reload replay at boot, and without this every reboot would re-run the
# last task anybody pressed Run now on.
if [ -f "$STATUS" ] && [ "$(published_id "$STATUS")" = "$REQ_ID" ]; then
  exit 0
fi

APP="$(jq -r '.app // ""' <<<"$REQ_JSON")"
TASK="$(jq -r '.task // ""' <<<"$REQ_JSON")"

# The allowlist is the load-bearing security control here: both strings become
# part of a systemd unit name that root then starts. RUNNABLE is generated in
# nix from the committed registry (site/apps.json), so it is exactly the set of
# `<app>:<task>` pairs that HAVE a unit — a task on a `declared` app has none,
# and anything else is an injection attempt. Matching the pair as one token is
# what stops an app's name being paired with another app's task id.
case " $RUNNABLE " in
*" $APP:$TASK "*) ;;
*)
  reject "unknown or non-runnable task: '$APP:$TASK'"
  ;;
esac

write_status running ""

# --wait blocks until the oneshot finishes and propagates its exit status, so
# a failed run is reported here rather than looking like a success that
# happened to leave a failed unit behind.
if systemctl start --wait "app-$APP-task-$TASK.service"; then
  write_status "done" ""
else
  write_status failed "app-$APP-task-$TASK.service failed — see journalctl -u app-$APP-task-$TASK"
  exit 1
fi
