import { describe, expect, it } from 'vitest'
import { type ImageFreshness, reconcileFreshness } from './images'

// Two clocks: the registry probe runs daily, the pin is regenerated by nix on
// every switch. The instant an update lands, the probe's row describes a ref
// the box has left — and keeps describing it for up to a day.
//
// Every case below is one that actually rendered wrong on this box: a
// freshly-updated wealthfolio offering `3.6.3 → 3.6.3, newer tag`, and the
// same shape latent on the channel-pin path where a re-pulled searxng would
// have read `tag moved` until the next nightly run.

const probe = (over: Partial<ImageFreshness> = {}): ImageFreshness => ({
  image: 'docker.io/afadil/wealthfolio:3.6.2',
  tag: '3.6.2',
  pinnedDigest: 'sha256:old',
  remoteDigest: 'sha256:old',
  moved: false,
  remoteCreated: null,
  newerTag: '3.6.3',
  candidates: ['3.6.3', '3.6.2', '3.6.1'],
  checkedAt: '2026-08-13T04:00:00-03:00',
  error: null,
  stale: false,
  ...over,
})

describe('a probe answer is spent by the update it prompted', () => {
  it('the tag it recommended, once taken, is no longer newer', () => {
    const r = reconcileFreshness(probe(), { tag: '3.6.3', digest: 'sha256:new' })
    expect(r.newerTag).toBeNull()
    expect(r.moved).toBe(false)
    expect(r.stale).toBe(true)
    // The live pin replaces the recollection of it.
    expect(r.pinnedDigest).toBe('sha256:new')
  })

  it('before the update, it still recommends the tag', () => {
    const r = reconcileFreshness(probe(), { tag: '3.6.2', digest: 'sha256:old' })
    expect(r.newerTag).toBe('3.6.3')
    expect(r.stale).toBe(false)
  })

  it('a channel pin that was re-pulled is no longer "moved"', () => {
    const f = probe({
      image: 'docker.io/searxng/searxng:latest',
      tag: 'latest',
      newerTag: null,
      candidates: [],
      remoteDigest: 'sha256:c7ca',
      moved: true,
    })
    expect(reconcileFreshness(f, { tag: 'latest', digest: 'sha256:c7ca' }).moved).toBe(false)
    // ...and still moved while the pin genuinely lags behind the channel.
    expect(reconcileFreshness(f, { tag: 'latest', digest: 'sha256:99e3' }).moved).toBe(true)
  })

  it('a remote digest recorded for a tag we have left proves nothing', () => {
    // intel-gpu-exporter: probed on 0.7.1, pin now 0.7.2. The recorded remote
    // digest is 0.7.1's, so comparing it to the new pin would read as "moved".
    const f = probe({
      tag: '0.7.1',
      remoteDigest: 'sha256:v071',
      candidates: ['0.7.2', '0.7.1', '0.7.0'],
      newerTag: '0.7.2',
    })
    const r = reconcileFreshness(f, { tag: '0.7.2', digest: 'sha256:v072' })
    expect(r.moved).toBe(false)
    expect(r.newerTag).toBeNull()
  })

  it('a tag the probe has never seen makes no claim either way', () => {
    // An operator-chosen tag outside the shortlist: index -1, so the only
    // checkable claim is the trivial one.
    const r = reconcileFreshness(probe(), { tag: '4.0.0-rc1', digest: 'sha256:rc' })
    expect(r.newerTag).toBe('3.6.3')
    expect(r.stale).toBe(true)
  })

  it('being top of the shortlist beats a stale newerTag', () => {
    const f = probe({ newerTag: '3.6.3', candidates: ['3.6.3', '3.6.2'] })
    expect(reconcileFreshness(f, { tag: '3.6.3', digest: 'x' }).newerTag).toBeNull()
  })

  it('an errored probe never reports movement', () => {
    const f = probe({ error: 'toomanyrequests', remoteDigest: null, moved: false })
    expect(reconcileFreshness(f, { tag: '3.6.2', digest: 'sha256:old' }).moved).toBe(false)
  })
})
