import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { type ImageFreshness, reconcileFreshness } from './images'

// Two clocks: the registry probe runs daily, the pin is regenerated by nix on
// every switch. The instant an update lands, the probe's row describes a ref
// the box has left — and keeps describing it for up to a day.
//
// Every case below is one that actually rendered wrong on this box: a
// freshly-updated wealthfolio offering `3.6.3 → 3.6.3, newer tag`, and the
// same shape latent on the channel-pin path where a re-pulled searxng would
// have read `tag moved` until the next nightly run.

const probe = (over: Partial<ImageFreshness> = {}): ImageFreshness => ({
  image: 'docker.io/afadil/wealthfolio:3.6.2',
  tag: '3.6.2',
  pinnedDigest: 'sha256:old',
  remoteDigest: 'sha256:old',
  moved: false,
  remoteCreated: null,
  remoteVersion: null,
  newerTag: '3.6.3',
  candidates: ['3.6.3', '3.6.2', '3.6.1'],
  checkedAt: '2026-08-13T04:00:00-03:00',
  error: null,
  stale: false,
  ...over,
})

describe('a probe answer is spent by the update it prompted', () => {
  it('the tag it recommended, once taken, is no longer newer', () => {
    const r = reconcileFreshness(probe(), { tag: '3.6.3', digest: 'sha256:new' })
    expect(r.newerTag).toBeNull()
    expect(r.moved).toBe(false)
    expect(r.stale).toBe(true)
    // The live pin replaces the recollection of it.
    expect(r.pinnedDigest).toBe('sha256:new')
  })

  it('before the update, it still recommends the tag', () => {
    const r = reconcileFreshness(probe(), { tag: '3.6.2', digest: 'sha256:old' })
    expect(r.newerTag).toBe('3.6.3')
    expect(r.stale).toBe(false)
  })

  it('a channel pin that was re-pulled is no longer "moved"', () => {
    const f = probe({
      image: 'docker.io/searxng/searxng:latest',
      tag: 'latest',
      newerTag: null,
      candidates: [],
      remoteDigest: 'sha256:c7ca',
      moved: true,
    })
    expect(reconcileFreshness(f, { tag: 'latest', digest: 'sha256:c7ca' }).moved).toBe(false)
    // ...and still moved while the pin genuinely lags behind the channel.
    expect(reconcileFreshness(f, { tag: 'latest', digest: 'sha256:99e3' }).moved).toBe(true)
  })

  it('a remote digest recorded for a tag we have left proves nothing', () => {
    // intel-gpu-exporter: probed on 0.7.1, pin now 0.7.2. The recorded remote
    // digest is 0.7.1's, so comparing it to the new pin would read as "moved".
    const f = probe({
      tag: '0.7.1',
      remoteDigest: 'sha256:v071',
      candidates: ['0.7.2', '0.7.1', '0.7.0'],
      newerTag: '0.7.2',
    })
    const r = reconcileFreshness(f, { tag: '0.7.2', digest: 'sha256:v072' })
    expect(r.moved).toBe(false)
    expect(r.newerTag).toBeNull()
  })

  it('a tag the probe has never seen makes no claim either way', () => {
    // An operator-chosen tag outside the shortlist: index -1, so the only
    // checkable claim is the trivial one.
    const r = reconcileFreshness(probe(), { tag: '4.0.0-rc1', digest: 'sha256:rc' })
    expect(r.newerTag).toBe('3.6.3')
    expect(r.stale).toBe(true)
  })

  it('being top of the shortlist beats a stale newerTag', () => {
    const f = probe({ newerTag: '3.6.3', candidates: ['3.6.3', '3.6.2'] })
    expect(reconcileFreshness(f, { tag: '3.6.3', digest: 'x' }).newerTag).toBeNull()
  })

  it('an errored probe never reports movement', () => {
    const f = probe({ error: 'toomanyrequests', remoteDigest: null, moved: false })
    expect(reconcileFreshness(f, { tag: '3.6.2', digest: 'sha256:old' }).moved).toBe(false)
  })
})

// ── the refinement rule ───────────────────────────────────────────────────
//
// A stock runtime image publishes no OCI labels and its tag names a LINE:
// `python:3.13-alpine` is every 3.13.x ever built. The precise release is in
// the config's PYTHON_VERSION, and using it is what makes a changelog say
// "one release pending" instead of sixteen.
//
// The guard is the point. This module's opening argument is that a
// label-first rule made Cleanuparr confidently report Ubuntu's `24.04`; a
// refinement that disagrees with the pin must therefore be discarded, not
// preferred.

let dir: string

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), 'imgver-'))
  process.env.IMAGE_LABELS_PATH = join(dir, 'labels.json')
  // A tag map with no entry falls back to the label path; each case below
  // supplies whichever half it is about.
  process.env.EXPORT_DIR = dir
})

afterEach(async () => {
  await rm(dir, { recursive: true, force: true })
  process.env.IMAGE_LABELS_PATH = undefined
  process.env.EXPORT_DIR = undefined
})

/**
 * Write both snapshots, then read the version through a FRESH module.
 *
 * Both readers sit behind a 60s swrValue cache (deliberately — they are
 * called several times per render). Sharing one module across these cases
 * would mean every test after the first asserted against the first one's
 * data, which is how the first draft of this block "passed" two cases it had
 * no right to.
 */
const versionOf = async (tag: string, configVersion: string | null): Promise<string | null> => {
  await writeFile(
    join(dir, 'images.json'),
    JSON.stringify({
      daedalusExport: 1,
      domain: 'images',
      schemaVersion: 2,
      source: 'nix',
      generatedAt: new Date().toISOString(),
      data: { tags: { subject: tag }, pins: {} },
    }),
  )
  await writeFile(
    join(dir, 'labels.json'),
    JSON.stringify({
      subject: { version: null, revision: null, source: null, created: null, configVersion },
    }),
  )

  vi.resetModules()
  const mod = await import('./images')
  return (await mod.imageVersion('subject')).version
}

describe('the config version sharpens the pin, never contradicts it', () => {
  it('a line tag is refined to the release actually in the image', async () => {
    expect(await versionOf('3.13-alpine', '3.13.15')).toBe('3.13.15')
  })

  it('it is still the pin speaking, not a third source', async () => {
    await versionOf('3.13-alpine', '3.13.15')
    vi.resetModules()
    const mod = await import('./images')
    expect((await mod.imageVersion('subject')).source).toBe('pin')
  })

  it('a config version that disagrees with the pin is discarded', async () => {
    // The Cleanuparr shape: pin says 2.10.1, the image says Ubuntu's 24.04.
    expect(await versionOf('2.10.1', '24.04')).toBe('2.10.1')
  })

  it('an equally precise config version adds nothing', async () => {
    expect(await versionOf('3.13.15', '3.13.15')).toBe('3.13.15')
  })

  it('a config version on a different line of the same major is discarded', async () => {
    expect(await versionOf('3.13-alpine', '3.12.9')).toBe('3.13')
  })

  it('no config version leaves the pin exactly as it was', async () => {
    expect(await versionOf('3.13-alpine', null)).toBe('3.13')
  })

  // A bare channel tag — nextcloud-redis is pinned to `alpine`. The pin
  // carries no version at all and the image publishes no OCI label, so
  // without this the dashboard reports a dash for a container whose exact
  // version is sitting in its own build config.
  it('answers for a channel tag, where nothing else can', async () => {
    expect(await versionOf('alpine', '8.8.1')).toBe('8.8.1')

    vi.resetModules()
    const mod = await import('./images')
    expect((await mod.imageVersion('subject')).source).toBe('config')
  })
})
