// Pocket ID: who can sign in to this house, and to what.
//
// A shared library rather than a category of its own, because two pages need
// it and neither owns it. Home's Sign-in tab is the subject — the IdP is the
// account every person here signs in with, and its audit log is the only place
// on the box that records a human being doing something. The proxy's page
// borrows the client list to say which of its routes are gated, which is one
// column on a table about routing.
//
// It WAS a category, back when it was the second half of the proxy's page and
// the argument was that neither half belonged to the other. That argument was
// about traefik. Against the rest of Home — the automation, the photos, the
// files, the pantry — this is plainly one of the household's own things: it is
// the list of people, and of what each of them can open.

import { localDay, since } from '../../format'
import { getJson } from '../../http'
import { key } from '../../keys'
import { type VersionGap, versionGap } from '../github'

/** How far back the activity columns go. A column per day, as on the AI tabs. */
const DAYS = 14

/** One OIDC client, and whether anybody has actually used it. */
type IdpClient = {
  id: string
  name: string
  /** Where it lives, parsed from its launch or callback URLs. */
  host: string | null
  /** Authorizations in the window. */
  used: number
  /** Already rendered — see `TraefikData.upSeconds` for why, not how. */
  lastAgo: string | null
  /** Restricted to named groups, rather than open to every account. */
  restricted: boolean
  /**
   * Which consumer this registration is FOR, when the hostname has more
   * than one and the answer disambiguates them. Null otherwise.
   *
   * An app can legitimately need two: the proxy gate authenticates with one
   * (callback `https://<host>/oidc/callback`, generated by the publish layer
   * from `webApps.auth = "oidc"`) and the app's own login round-trips through
   * its own paths. They cannot be merged — the derived one would overwrite
   * the hand-written callbacks on every rebuild — so a pair here is a design,
   * not a leftover. This page called it a "duplicate" and invented a rename
   * to explain it, which was wrong on both counts.
   *
   * Labelled only for a shared hostname: on the other thirty-one it is noise,
   * because there is nothing to tell apart.
   */
  role: 'gate' | 'app' | null
  /** Another registration answers for the same hostname. */
  sharesHost: boolean
  /**
   * The individual authorizations behind `used`, newest first.
   *
   * Carried but not shown until a row is opened. The list of every sign-in on
   * the box is a log, and a log is what Grafana and Pocket ID's own audit page
   * are for — but "who opened THIS one, from what" is a question you ask about
   * a row you are already looking at, and paying a page load to answer it
   * elsewhere is worse than carrying eight rows that are already in memory.
   */
  opens: {
    id: string
    ago: string
    username: string
    device: string
    /**
     * A consent record was CREATED here, rather than an existing one reused.
     *
     * Not "the first time somebody used this app", which is how it was
     * labelled and is wrong — the event recurs, and an access older than it
     * sitting below it in the list is what gives that away. Pocket ID drops
     * the stored authorization whenever the client is rewritten, and
     * `pocket-id-clients.service` rewrites every client on every rebuild (a
     * full PUT of the body, plus a write of the secret, both unconditional).
     * So this marks where a rebuild made everyone consent again.
     */
    consent: boolean
  }[]
}

type IdpUser = {
  username: string
  displayName: string
  admin: boolean
  disabled: boolean
  /**
   * The principal behind STATIC_API_KEY, not a person.
   *
   * Pocket ID materialises the static API key as a real admin account, so it
   * appears in the user list and would otherwise make a one-person box read
   * as two. Worth showing rather than filtering — it IS an admin account, and
   * one nobody would think to look for — but not worth counting as somebody.
   */
  service: boolean
  groups: string[]
  signIns: number
  lastSignInAgo: string | null
}

export type IdpData = {
  version: string | null
  gap: VersionGap
  clients: IdpClient[]
  users: IdpUser[]
  groups: { name: string; members: number }[]
  /**
   * What holds a key to this house, newest first.
   *
   * The raw sign-in stream used to be here and it was the wrong thing: ten
   * rows of "signed in · santito · Chrome · 24h ago" is a log, and Grafana and
   * Pocket ID's own audit page already are one. Per DEVICE is the reading this
   * page can add — a passkey is registered to a device, so this is the list of
   * things that can authenticate as somebody, which is short, changes rarely,
   * and is worth noticing when it grows.
   */
  devices: { name: string; signIns: number; lastAgo: string }[]
  /** Authorizations per day, oldest first. */
  daily: { date: string; authorizations: number }[]
  window: {
    days: number
    signIns: number
    authorizations: number
    /**
     * Consent records created. NOT first-ever uses — see `opens[].consent`.
     * On this box it is mostly the convergence job invalidating consent on
     * a rebuild, which is why it is a two-figure number for thirty clients
     * nobody newly adopted.
     */
    consents: number
    /** People, so not the static-API-key principal. */
    people: number
  }
  /** Whether anyone can create an account. Read back, not restated. */
  signups: string | null
  /** The audit log went back further than the pages we were willing to read. */
  truncated: boolean
}
export type PocketClient = {
  id?: string
  name?: string
  launchURL?: string
  callbackURLs?: string[]
  isGroupRestricted?: boolean
}

export async function idpClients(base: string): Promise<PocketClient[]> {
  const body = await getJson<{ data?: PocketClient[] }>(
    // 100 against a box that has 33: one page, and a second page would be a
    // second round trip to discover there was nothing on it.
    `${base}/api/oidc/clients?pagination[limit]=100`,
    { headers: { 'X-API-KEY': key('POCKETID_KEY') } },
  )
  return body?.data ?? []
}

/**
 * Is this the registration the traefik forward-auth middleware signs in with.
 *
 * Matched on the callback, because that is the one thing the generator fixes:
 * `platform`'s publish layer emits exactly `https://<host>/oidc/callback` for
 * every `webApps.auth = "oidc"` entry, and an app's own login never uses that
 * path — it round-trips through whatever its framework mounts. Pocket ID's API
 * exposes no flag for this, so the URL is the tell.
 */
export function forwardAuthClient(c: PocketClient, host: string): boolean {
  const urls = c.callbackURLs ?? []
  return urls.length === 1 && urls[0] === `https://${host}/oidc/callback`
}

/** The hostname a client is for, from whichever URL it published. */
export function clientHost(c: PocketClient): string | null {
  const url = c.launchURL ?? c.callbackURLs?.[0] ?? ''
  try {
    return new URL(url).hostname
  } catch {
    // A native app's callback is a custom scheme (`app.immich:///oauth-callback`)
    // with no hostname at all. Not a fault — it just cannot name a route.
    return null
  }
}

type AuditEvent = {
  id?: string
  createdAt?: string
  event?: string
  username?: string
  device?: string
  city?: string
  country?: string
  data?: { clientName?: string }
}

/**
 * The audit log, back as far as the window.
 *
 * Paged because Pocket ID caps a page at a hundred and this box logs a couple
 * of hundred a fortnight. Bounded at six pages rather than "until the window
 * is covered": an instance that suddenly logs thousands a day should slow this
 * page down by nothing, and a truncated count that says so is better than a
 * complete one that arrives late.
 */
async function auditLog(
  base: string,
  sinceMs: number,
): Promise<{ events: AuditEvent[]; truncated: boolean }> {
  const h = { headers: { 'X-API-KEY': key('POCKETID_KEY') } }
  const events: AuditEvent[] = []

  for (let page = 1; page <= 6; page++) {
    const body = await getJson<{ data?: AuditEvent[]; pagination?: { totalPages?: number } }>(
      `${base}/api/audit-logs/all?pagination[limit]=100&pagination[page]=${String(page)}` +
        `&sort[column]=createdAt&sort[direction]=desc`,
      h,
    )
    const rows = body?.data ?? []
    events.push(...rows)
    if (rows.length === 0) return { events, truncated: false }
    if (page >= (body?.pagination?.totalPages ?? page)) return { events, truncated: false }
    // The page we just read reaches past the window, so nothing older matters.
    const oldest = Date.parse(rows[rows.length - 1]?.createdAt ?? '')
    if (Number.isFinite(oldest) && oldest < sinceMs) return { events, truncated: false }
  }
  return { events, truncated: true }
}

/**
 * Pocket ID: every account, every registered application, and who used what.
 *
 * The audit log is the whole panel, and it is the only place on this box that
 * records a sign-in at all — traefik's access log sees a 302 to the IdP and a
 * 200 afterwards, and cannot tell which human that was. Everything else here
 * (clients, users, groups) is configuration, and it is worth showing next to
 * the log for one reason: the difference between the two. A registered client
 * nobody has ever authorised is a redirect URI still trusted for an app that
 * may not exist.
 */
export async function loadIdp(base: string, clientsP: Promise<PocketClient[]>): Promise<IdpData> {
  const h = { headers: { 'X-API-KEY': key('POCKETID_KEY') } }
  const windowStart = Date.now() - DAYS * 86400_000
  const version = process.env.POCKET_ID_VERSION || null

  const [clients, users, groups, log, config, gap] = await Promise.all([
    clientsP,
    getJson<{ data?: PocketUser[] }>(`${base}/api/users?pagination[limit]=100`, h),
    getJson<{ data?: { name?: string; friendlyName?: string; userCount?: number }[] }>(
      `${base}/api/user-groups?pagination[limit]=100`,
      h,
    ),
    auditLog(base, windowStart),
    getJson<{ key?: string; value?: string }[]>(`${base}/api/application-configuration`, h),
    versionGap('pocket-id/pocket-id', version),
  ])

  const recent = log.events
    .map((e) => ({ ...e, at: Date.parse(e.createdAt ?? '') }))
    .filter((e) => Number.isFinite(e.at) && e.at >= windowStart)

  const AUTHORIZED = new Set(['CLIENT_AUTHORIZATION', 'NEW_CLIENT_AUTHORIZATION'])
  const SIGNED_IN = new Set(['SIGN_IN', 'TOKEN_SIGN_IN'])

  // Keyed by client NAME, because the name is all the audit log records. A
  // client that was renamed therefore reads as unused, which is the honest
  // answer — its old authorizations belong to a name that no longer exists.
  //
  // `opens` keeps the individual events too, capped: they are the drill-down
  // behind a row, and the eighth one has stopped answering "who has been in
  // here lately" and started being a log.
  const used = new Map<string, { n: number; last: number; opens: IdpClient['opens'] }>()
  for (const e of recent) {
    const name = e.data?.clientName
    if (name === undefined || !AUTHORIZED.has(e.event ?? '')) continue
    const hit = used.get(name) ?? { n: 0, last: 0, opens: [] }
    if (hit.opens.length < 8) {
      hit.opens.push({
        id: e.id ?? `${name}-${String(e.at)}`,
        ago: since((Date.now() - e.at) / 1000),
        username: e.username ?? '?',
        device: (e.device ?? '').trim() || 'unknown device',
        consent: e.event === 'NEW_CLIENT_AUTHORIZATION',
      })
    }
    used.set(name, { n: hit.n + 1, last: Math.max(hit.last, e.at), opens: hit.opens })
  }

  // What can authenticate as somebody. A passkey belongs to a device, so the
  // device string IS the credential — grouped rather than listed, because the
  // list is a log and the group is an inventory.
  const devices = new Map<string, { n: number; last: number }>()
  for (const e of recent) {
    if (!SIGNED_IN.has(e.event ?? '')) continue
    const name = (e.device ?? '').trim() || 'unknown device'
    const hit = devices.get(name) ?? { n: 0, last: 0 }
    devices.set(name, { n: hit.n + 1, last: Math.max(hit.last, e.at) })
  }

  const byHost = new Map<string, number>()
  for (const c of clients) {
    const host = clientHost(c)
    if (host !== null) byHost.set(host, (byHost.get(host) ?? 0) + 1)
  }

  const signIns = new Map<string, { n: number; last: number }>()
  for (const e of recent) {
    if (!SIGNED_IN.has(e.event ?? '')) continue
    const who = e.username ?? ''
    const hit = signIns.get(who) ?? { n: 0, last: 0 }
    signIns.set(who, { n: hit.n + 1, last: Math.max(hit.last, e.at) })
  }

  const byDay = new Map<string, number>()
  for (let i = DAYS - 1; i >= 0; i--) byDay.set(localDay(Date.now() - i * 86400_000), 0)
  for (const e of recent) {
    if (!AUTHORIZED.has(e.event ?? '')) continue
    const day = localDay(e.at)
    if (byDay.has(day)) byDay.set(day, (byDay.get(day) ?? 0) + 1)
  }

  // Pocket ID gives the static-API-key principal the all-zero UUID, which is
  // the only thing distinguishing it from a person — its username is generated
  // and its display name is whatever the release happened to call it.
  const people = (users?.data ?? []).filter((u) => u.id !== '00000000-0000-0000-0000-000000000000')

  return {
    version,
    gap,
    // Ordered by RECENCY, not by volume. The question a registration list
    // answers is "is this still a thing" — the live ones surface, the stale
    // ones sink, and the never-opened land at the bottom where they read as
    // the tail of one list rather than as a sentence somewhere else. Volume
    // is on the row; it is not what the order is for.
    clients: clients
      .map((c) => {
        const name = c.name ?? '?'
        const hit = used.get(name)
        const host = clientHost(c)
        return {
          id: c.id ?? name,
          name,
          host,
          used: hit?.n ?? 0,
          lastAgo: hit === undefined ? null : since((Date.now() - hit.last) / 1000),
          restricted: c.isGroupRestricted === true,
          sharesHost: host !== null && (byHost.get(host) ?? 0) > 1,
          role:
            host === null || (byHost.get(host) ?? 0) < 2
              ? null
              : forwardAuthClient(c, host)
                ? ('gate' as const)
                : ('app' as const),
          opens: hit?.opens ?? [],
          sortAt: hit?.last ?? 0,
        }
      })
      .sort((a, b) => b.sortAt - a.sortAt || a.name.localeCompare(b.name))
      .map(({ sortAt: _sortAt, ...c }) => c),
    users: (users?.data ?? [])
      .map((u) => {
        const hit = signIns.get(u.username ?? '')
        return {
          username: u.username ?? '?',
          displayName: u.displayName ?? u.username ?? '?',
          admin: u.isAdmin === true,
          disabled: u.disabled === true,
          service: u.id === '00000000-0000-0000-0000-000000000000',
          groups: (u.userGroups ?? []).map((g) => g.friendlyName ?? g.name ?? '?'),
          signIns: hit?.n ?? 0,
          lastSignInAgo: hit === undefined ? null : since((Date.now() - hit.last) / 1000),
          // Sort key only. Kept off the type so nothing renders it and
          // reintroduces the clock the strings above exist to avoid.
          sortAt: hit?.last ?? 0,
        }
      })
      .sort((a, b) => b.sortAt - a.sortAt)
      .map(({ sortAt: _sortAt, ...u }) => u),
    groups: (groups?.data ?? []).map((g) => ({
      name: g.friendlyName ?? g.name ?? '?',
      members: g.userCount ?? 0,
    })),
    devices: [...devices]
      .map(([name, d]) => ({
        name,
        signIns: d.n,
        lastAgo: since((Date.now() - d.last) / 1000),
        sortAt: d.last,
      }))
      .sort((a, b) => b.sortAt - a.sortAt)
      .map(({ sortAt: _sortAt, ...d }) => d),
    daily: [...byDay].map(([date, authorizations]) => ({ date, authorizations })),
    window: {
      days: DAYS,
      signIns: recent.filter((e) => SIGNED_IN.has(e.event ?? '')).length,
      authorizations: recent.filter((e) => AUTHORIZED.has(e.event ?? '')).length,
      consents: recent.filter((e) => e.event === 'NEW_CLIENT_AUTHORIZATION').length,
      people: people.length,
    },
    signups: (config ?? []).find((c) => c.key === 'allowUserSignups')?.value ?? null,
    truncated: log.truncated,
  }
}

type PocketUser = {
  id?: string
  username?: string
  displayName?: string
  isAdmin?: boolean
  disabled?: boolean
  userGroups?: { name?: string; friendlyName?: string }[]
}
