/** The signature motif: the icon's square labyrinth extended to ten rings,
 * still ONE unbroken axis-aligned stroke from the center out. Generated by
 * the same inward-spiral rule as the 32px mark (segment pairs of s, 2s, 3s …
 * cycling down/left/up/right); at s=4, six pairs, it reproduces the icon
 * path exactly.
 *
 * `pathLength=1` normalizes the whole spiral to a single dash unit so the
 * CSS draw-on (.labyrinth-draw in styles.css) can walk it in from the
 * center. `vector-effect: non-scaling-stroke` keeps the line hairline-thin
 * no matter how large the SVG renders. */
const LABYRINTH_PATH =
  "M88 88 L88 96 L80 96 L80 80 L96 80 L96 104 L72 104 L72 72 L104 72 L104 112 " +
  "L64 112 L64 64 L112 64 L112 120 L56 120 L56 56 L120 56 L120 128 L48 128 " +
  "L48 48 L128 48 L128 136 L40 136 L40 40 L136 40 L136 144 L32 144 L32 32 " +
  "L144 32 L144 152 L24 152 L24 24 L152 24 L152 160 L16 160 L16 16 L160 16 " +
  "L160 168 L8 168 L8 8 L168 8";

export function Labyrinth({
  className = "",
  strokeWidth = 1.5,
  draw = false,
}: {
  className?: string;
  strokeWidth?: number;
  draw?: boolean;
}) {
  return (
    <svg viewBox="0 0 176 176" fill="none" className={className} aria-hidden>
      <path
        d={LABYRINTH_PATH}
        pathLength={1}
        stroke="var(--color-accent)"
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
        vectorEffect="non-scaling-stroke"
        className={draw ? "labyrinth-draw" : undefined}
      />
    </svg>
  );
}
