# wg-easy — WireGuard server + admin web UI.
#
# Ports:
#   - 51820/udp — WireGuard protocol. Host-firewall-opened
#     (allowedUDPPorts below); reach via fleet.wanHost:51820, which pi-hole
#     also answers with the LAN address — so a profile generated once works
#     both at home (straight to the box) and away, with no second endpoint.
#   - 51821/tcp — admin web UI; bridge-routed via traefik (no host port).
#
# Caps + sysctls:
#   - NET_ADMIN: lets wg-easy create wg0 inside the container's netns.
#   - NET_RAW: kept from the iptables-legacy days (its raw sockets for
#     netfilter state queries; NET_ADMIN alone returned "Permission denied").
#   - net.ipv4.ip_forward: routing between wg0 and the container's eth0.
#   - net.ipv4.conf.all.src_valid_mark: WireGuard mark-based routing.
#
# `SYS_MODULE` is NOT needed — the wireguard kernel module is loaded
# on the host (boot.kernelModules below); container just needs
# /lib/modules read-only to find it.
#
# iptables is nf_tables, never legacy. The image's `iptables` is an
# alternatives link to iptables-legacy, and every rule wg-easy writes goes
# through it: the PostUp/PostDown hooks (stored in wg-easy.db, run by
# wg-quick) and the per-client firewall. A kernel without the legacy
# ip_tables (6.18 as NixOS 26.05 builds it) has no `nat` table for it, and
# `wg-quick up wg0` fails with "Table does not exist". So the container gets
# a read-only /etc/alternatives whose links name the image's own
# iptables-nft binaries: the hooks in the database keep saying `iptables`
# and run on nf_tables, with nothing to edit in the app. The host-ports
# oneshot below names iptables-nft outright.
#
# ── auth: native OIDC against Pocket ID (v15.4.0+) ─────────────────────
#
# wg-easy's generic OIDC provider (`OAUTH_PROVIDERS=oidc`) is a Tier-1
# client: openid-client fetches discovery from OAUTH_OIDC_SERVER at
# request time (so no `sso.discoveryConsumers` entry — an IdP outage
# breaks the login page, not the container), PKCE S256, client secret
# via client_secret_post, `openid email profile`. The client secret is
# machine-generated by the identity provider's module and rendered in as
# OAUTH_OIDC_CLIENT_{ID,SECRET} through `consumers`. Two redirect URIs:
# /api/auth/oidc/callback (login) and /api/auth/oidc/link (attaching the
# provider to an already-signed-in account).
#
# Users match on the IdP `sub`, not on email, so the pre-OIDC local
# admin is a different account from the Pocket ID one. OAUTH_AUTO_REGISTER
# creates the latter at first login — "with Admin Permissions, as the
# permissions system is not yet implemented" (upstream's words), which
# is acceptable ONLY because the Pocket ID client is restricted to the
# `admins` group (ssoClients' default allowedGroups): nobody the IdP lets
# through this client is not already the operator. OAUTH_AUTO_LAUNCH
# sends /login straight to Pocket ID; `/login?auto_launch=false` shows
# the password form.
#
# The pre-OIDC admin stays in wg-easy.db. The WireGuard tunnel itself never
# depends on any of this: :51820 is key-authenticated and stays up whether
# or not the UI can log in.
#
# Passwords are ON (DISABLE_PASSWORD_AUTH=false) for one reason: the
# control plane's API calls. wg-easy's API takes HTTP Basic auth — and
# only for a password account without TOTP — so passwords stay enabled
# for the one password account there is, the INIT admin
# (INIT_USERNAME/INIT_PASSWORD in the host's env file; wg-easy 15 has no
# way to create a second user — no users API, and INIT runs on an empty
# database alone). Its password must be the one in that file (change it
# in the UI, then in the file, together) and it must have no TOTP.
# Browsers still meet OIDC first: OAUTH_AUTO_LAUNCH sends /login to
# Pocket ID, and `/login?auto_launch=false` is the password form — on the
# LAN alone, as the whole UI is (no exposeRemotely). Anyone who can reach
# :51821 — a traefik-net member, a peer on the tunnel at 10.8.0.1 — can
# try that password, so it is a long random one.
#
# ── the control plane's API path ────────────────────────────────────────
#
# daedalus signs a machine in (the agent's "Log in", enroll.rs in the
# agent) by creating it as an ordinary wg-easy client, and removes the
# client when the machine logs out or is revoked. It calls wg-easy's API
# directly on a bridge of its own — `wg-easy-api`, just these two
# containers, never traefik — as the INIT admin, with Basic auth. The
# bridge is `--internal` (fleet.internalBridges): no default route on
# wg-easy's side of it, so the tunnel's egress and its MASQUERADE stay on
# eth0, the traefik bridge (listed first: podman numbers the interfaces in
# the order of its --network flags). Handed to the control plane
# (fleet.dashboard.wg-easy):
#   WG_EASY_URL          http://wg-easy:51821 on that bridge
#   WG_EASY_CREDENTIALS  a file holding `username:password` (the Basic
#                        userinfo), rendered from the host's env file —
#                        the one copy of the secret, read per call so a
#                        rotation needs no restart of the app
#   WG_EASY_HOST_ALIAS   where the tunnel's host ports land after the DNAT
#                        below: an agent client's per-client firewall
#                        names this address (`<alias>:7788/tcp`), not the
#                        LAN address, because wg-easy filters in FORWARD,
#                        after PREROUTING rewrote the destination.
# Holding this admin is no escalation for the control plane: it already
# builds and runs arbitrary containers as the operator.
#
# The IdP side has one per-user requirement: wg-easy 401s
# "Email is not verified" unless userinfo carries email_verified=true,
# so every Pocket ID user that should reach this UI needs "Email
# verified" ticked.
#
# The host brings:
#   fleet.modules.wg-easy.enable       the switch (default off, as every catalog module)
#   fleet.modules.wg-easy.envSopsFile  INIT_USERNAME, INIT_PASSWORD (first-init admin,
#                                      and the control plane's API account)
#   fleet.images.wg-easy               the digest-pinned image
# The tunnel's public address is `fleet.wanHost`; the port (51820/udp) must be
# forwarded to the box by the router.

{
  config,
  lib,
  pkgs,
  mkRootlessContainer,
  mkDotenvSecret,
  mkSecretRender,
  pinnedImage,
  ...
}:

let
  cfg = config.fleet.modules.wg-easy;
  # The control plane is on this box (its container exists): it gets the API
  # path (the header).
  controlPlane = config.fleet.modules.daedalus.enable && config.fleet.modules.apps.enable;
  credentialsDir = "/run/wg-easy-daedalus";
  inherit (config.fleet.webApps.wg-easy) hostname;

  # The container's /etc/alternatives (see the header): each iptables name
  # points at the image's own nf_tables binary. Links into the container's
  # filesystem, resolved there.
  nftAlternatives = pkgs.runCommand "wg-easy-iptables-nft" { } ''
    mkdir $out
    for t in iptables ip6tables; do
      ln -s /usr/sbin/$t-nft $out/$t
      ln -s /usr/sbin/$t-nft-restore $out/$t-restore
      ln -s /usr/sbin/$t-nft-save $out/$t-save
    done
  '';
in
{
  options.fleet.modules.wg-easy = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "wg-easy — WireGuard server and admin UI.";
    };

    envSopsFile = lib.mkOption {
      type = lib.types.path;
      example = lib.literalExpression "./host/sops/wg-easy/env.sops";
      description = ''
        sops-encrypted dotenv carrying INIT_USERNAME and INIT_PASSWORD, the
        local admin a fresh database is initialised with — and the account
        the control plane calls the API as, so the password must stay the
        one that admin has (the header). Host data: the engine carries no box's ciphertext.
        Only read while the module is on.
      '';
    };

    tunnelHostPorts = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            port = lib.mkOption {
              type = lib.types.port;
              description = "The host port.";
            };
            proto = lib.mkOption {
              type = lib.types.enum [
                "tcp"
                "udp"
              ];
              default = "tcp";
              description = "Its protocol.";
            };
          };
        }
      );
      default = [ ];
      example = [ { port = 22; } ];
      description = ''
        Host ports a peer on the tunnel reaches at the LAN address although
        the router does not forward them — the same DNAT the forwarded ports
        get (see `wg-easy-host-ports` in the module). For a service a peer
        should find at the one address it uses at home: sshd, the
        controller's link. Whoever needs the port adds it; empty by default.
        Only read while the module is on.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # INIT_USERNAME + INIT_PASSWORD, decrypted to /run/secrets/wg-easy-env
    # at activation from the host's `envSopsFile`.
    sops.secrets."wg-easy-env" = mkDotenvSecret cfg.envSopsFile;

    # Pocket ID client — id `wg-easy`, secret generated on the box, rendered
    # into the container as the OAUTH_OIDC_* pair. PKCE stays on (default):
    # wg-easy sends S256. No `logo` here: the sync falls back to
    # `wg-easy.png` in the host's fleet.sso.logoDir, when it has one.
    fleet.ssoClients.wg-easy = {
      displayName = "WireGuard";
      description = "VPN — peers + profiles";
      launchURL = "https://${hostname}";
      callbackURLs = [
        "https://${hostname}/api/auth/oidc/callback"
        "https://${hostname}/api/auth/oidc/link"
      ];
      logoutCallbackURLs = [ "https://${hostname}/login" ];
      consumers = [ "wg-easy" ];
      consumerEnv = {
        id = "OAUTH_OIDC_CLIENT_ID";
        secret = "OAUTH_OIDC_CLIENT_SECRET";
      };
    };

    # `traefik` first and eth0: the tunnel's egress (the header).
    fleet.bridgeMemberships.wg-easy = [ "traefik" ] ++ lib.optional controlPlane "wg-easy-api";
    fleet.bridgeMemberships.app-daedalus = lib.mkIf controlPlane [ "wg-easy-api" ];
    fleet.internalBridges = lib.optional controlPlane "wg-easy-api";

    # What the control plane reads (the header): where the API is, the file
    # with the Basic credentials, and where the tunnel's host ports land.
    fleet.dashboard.wg-easy = lib.mkIf controlPlane {
      env = {
        WG_EASY_URL = "http://wg-easy:51821";
        WG_EASY_CREDENTIALS = "/wg-easy/credentials";
        WG_EASY_HOST_ALIAS = config.fleet.podman.hostAlias;
      };
      volumes = [ "${credentialsDir}:/wg-easy:ro" ];
    };
    systemd.services.wg-easy-daedalus-credentials = lib.mkIf controlPlane (mkSecretRender {
      description = "Render wg-easy's API credentials for daedalus";
      gates = [ "podman-app-daedalus.service" ];
      dir = credentialsDir;
      file = "${credentialsDir}/credentials";
      prep = ''
        USERNAME=$(grep -m1 '^INIT_USERNAME=' ${config.sops.secrets."wg-easy-env".path} | cut -d= -f2-)
        PASSWORD=$(grep -m1 '^INIT_PASSWORD=' ${config.sops.secrets."wg-easy-env".path} | cut -d= -f2-)
      '';
      content = "$USERNAME:$PASSWORD";
    });
    fleet.webApps.wg-easy = {
      serviceName = "wg-easy";
      port = 51821;
      metrics = {
        enable = true;
        path = "/metrics/prometheus";
      };
    };

    # A gluetun tunnel (platform/lib/gluetun-lib.nix) adds the same modules;
    # NixOS merges the lists.
    # nf_tables and the iptables-nft pieces the hooks use (nat chains,
    # MASQUERADE, DNAT): loaded up front rather than left to autoload from
    # inside a user namespace. Never the legacy iptable_*: 6.18 has none.
    boot.kernelModules = [
      "wireguard"
      "nf_tables"
      "nft_compat"
      "nft_chain_nat"
      "xt_MASQUERADE"
      "xt_nat"
    ];

    # The router forwards this port to the box — see fleet.directIngress. The
    # tunnel carries HTTP only, and WireGuard is UDP.
    fleet.directIngress.wireguard = {
      port = 51820;
      note = "A WireGuard socket does not answer an unauthenticated packet at all, which is the entire reason a forwarded port is acceptable here.";
    };

    networking.firewall.allowedUDPPorts = [ 51820 ];

    # ── host ports, at the LAN address, over the tunnel ───────────────────
    #
    # A peer at home types the LAN address (the WAN host resolves to it
    # through pi-hole), and so does a peer on the tunnel — but inside this
    # container's rootless netns the LAN address is the netns ITSELF (pasta
    # copies the host's address in), so a connection to it reaches only what
    # is published inside the netns: the bridge ports (80/443) answer, and a
    # port published on the host by its own pasta instance (a game server
    # kept off the bridge for its client addresses) is refused, as is a
    # service on the host itself (sshd). The host is `fleet.podman.hostAlias`
    # here, pasta's alias for it.
    #
    # So every port the router forwards (fleet.directIngress — the ones meant
    # to be reached from anywhere), and every `tunnelHostPorts` entry (a host
    # port a peer should find at the LAN address without the router
    # forwarding it), that the netns does NOT already serve is DNATed from
    # the LAN address to that alias, exactly as the DNS hook does for
    # 10.8.0.1:53. A port a bridge member publishes is served in the netns by
    # rootlessport and already works; it is left alone rather than rerouted.
    # pasta dials the host from the host itself, so the connection arrives on
    # loopback: a port the firewall opens on the LAN interface only is
    # reached all the same. Converged after every container start; `-C`
    # first, so a re-run adds nothing twice (a port dropped from the set
    # keeps its rule until the container restarts).
    systemd.services.wg-easy-host-ports =
      let
        bridgePublished = lib.concatLists (
          lib.mapAttrsToList (
            n: c: if (config.fleet.bridgeMemberships.${n} or [ ]) != [ ] then c.ports else [ ]
          ) config.virtualisation.oci-containers.containers
        );
        # `[ip:]host:container[/proto]`, tcp when the proto is left out.
        publishes =
          i: p:
          let
            m = builtins.match "(.*:)?([0-9]+):[0-9]+(/(tcp|udp))?" p;
          in
          m != null
          && builtins.elemAt m 1 == toString i.port
          && (if builtins.elemAt m 3 == null then "tcp" else builtins.elemAt m 3) == i.proto;
        wanted = lib.unique (
          map (i: { inherit (i) port proto; }) (
            lib.attrValues config.fleet.directIngress ++ cfg.tunnelHostPorts
          )
        );
        ports = lib.filter (
          i: !(i.port == 51820 && i.proto == "udp") && !lib.any (publishes i) bridgePublished
        ) wanted;
        rule =
          i:
          "-d ${config.fleet.lanIp}/32 -i wg0 -p ${i.proto} -m ${i.proto} --dport ${toString i.port} -j DNAT --to-destination ${config.fleet.podman.hostAlias}:${toString i.port}";
      in
      lib.mkIf (ports != [ ]) {
        description = "Reach host ports at the LAN address from the WireGuard tunnel";
        after = [ "podman-wg-easy.service" ];
        partOf = [ "podman-wg-easy.service" ];
        wantedBy = [
          "podman-wg-easy.service"
          "multi-user.target"
        ];
        path = [
          pkgs.podman
          pkgs.util-linux
          pkgs.coreutils
        ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          set -euo pipefail
          wg() {
            setpriv --reuid=${config.fleet.operator.user} --regid=${config.fleet.operator.group} --init-groups --inh-caps=-all \
              env HOME=${config.fleet.operator.home} XDG_RUNTIME_DIR=${config.fleet.operator.runtimeDir} \
              podman exec wg-easy iptables-nft -t nat "$@"
          }
          for _ in $(seq 1 30); do
            wg -S PREROUTING > /dev/null 2>&1 && break
            sleep 2
          done
          ${lib.concatMapStrings (i: ''
            wg -C PREROUTING ${rule i} 2>/dev/null || wg -A PREROUTING ${rule i}
          '') ports}
          echo "tunnel reaches ${
            lib.concatMapStringsSep ", " (i: "${toString i.port}/${i.proto}") ports
          } at ${config.fleet.lanIp}"
        '';
      };

    fleet.statePaths = {
      # Non-traversable parent closes the world-readable window if wg-easy
      # rewrites its db loosely; container root maps to the operator, so the
      # bind mount still works.
      "${config.fleet.stateRoot}/wg-easy".mode = "0700";
      # wg-easy writes wg-easy.db (server private key + client configs/PSKs)
      # world-readable (0644). state-paths re-tightens it to 0600 at boot —
      # a private key has no business being world-readable, even on a
      # single-user box. (tmpfiles can't do this: it silently skips rules
      # under the operator-owned /home prefix. `f` pre-creates the file
      # empty if missing, which SQLite treats as a valid empty DB.)
      "${config.fleet.stateRoot}/wg-easy/wg-easy.db" = {
        type = "f";
        mode = "0600";
      };
    };

    virtualisation.oci-containers.containers.wg-easy = mkRootlessContainer {
      image = pinnedImage "wg-easy" "ghcr.io/wg-easy/wg-easy";

      ports = [
        "51820:51820/udp"
      ];

      volumes = [
        "${config.fleet.stateRoot}/wg-easy:/etc/wireguard"
        # NixOS keeps kernel modules under /run/booted-system, not
        # /lib/modules. Belt-and-suspenders bind (the module is loaded).
        "/run/booted-system/kernel-modules/lib/modules:/lib/modules:ro"
        # iptables = iptables-nft inside the container (the header).
        "${nftAlternatives}:/etc/alternatives:ro"
      ];

      environment = {
        INIT_ENABLED = "true";
        INIT_HOST = config.fleet.wanHost;
        INIT_PORT = "51820";
        # Client DNS must be the wg0 address (10.8.0.1), NOT a host IP:
        # - the LAN address is unreachable from the container netns (pasta
        #   copies the host IP into the namespace; port 53 has no netns
        #   listener, so queries die with "connection refused").
        # - 169.254.1.2 (pasta host alias) IS reachable from the netns,
        #   but clients never send it through the tunnel: 169.254/16 is
        #   link-local and stays pinned to the physical interface on
        #   macOS/iOS, beating the tunnel /1 routes.
        # A PostUp DNAT hook (stored in wg-easy.db, NOT re-created on a
        # fresh init — re-add via admin UI > Hooks if bootstrapping!)
        # forwards 10.8.0.1:53 -> 169.254.1.2:53 -> host pi-hole.
        INIT_DNS = "10.8.0.1";
        DISABLE_IPV6 = "true";

        # Pocket ID SSO — see the header. Client id/secret arrive via the
        # ssoClients consumer env file; everything non-secret is here.
        OAUTH_PROVIDERS = "oidc";
        OAUTH_OIDC_SERVER = config.fleet.sso.issuerUrl;
        OAUTH_OIDC_NAME = "Pocket ID";
        OAUTH_AUTO_REGISTER = "true";
        OAUTH_AUTO_LAUNCH = "oidc";
        # The control plane's Basic auth needs it (the header).
        DISABLE_PASSWORD_AUTH = "false";
      };

      # INIT_USERNAME + INIT_PASSWORD (first-init admin credentials; inert
      # once wg-easy.db exists). The OIDC client pair is appended by
      # the identity provider's client sync (pocket-id/clients.nix) via
      # `consumers` above.
      environmentFiles = [
        config.sops.secrets."wg-easy-env".path
      ];

      extraOptions = [
        "--cap-add=NET_ADMIN"
        "--cap-add=NET_RAW"
        "--sysctl=net.ipv4.ip_forward=1"
        "--sysctl=net.ipv4.conf.all.src_valid_mark=1"
      ];
    };
  };
}
