# wg-easy — WireGuard server + admin web UI.
#
# Ports:
#   - 51820/udp — WireGuard protocol. Host-firewall-opened
#     (allowedUDPPorts below); reach via fleet.wanHost:51820, which pi-hole
#     also answers with the LAN address — so a profile generated once works
#     both at home (straight to the box) and away, with no second endpoint.
#   - 51821/tcp — admin web UI; bridge-routed via traefik (no host port).
#
# Caps + sysctls:
#   - NET_ADMIN: lets wg-easy create wg0 inside the container's netns.
#   - NET_RAW: iptables-legacy raw sockets for netfilter state queries
#     (NET_ADMIN alone returns "Permission denied").
#   - net.ipv4.ip_forward: routing between wg0 and the container's eth0.
#   - net.ipv4.conf.all.src_valid_mark: WireGuard mark-based routing.
#
# `SYS_MODULE` is NOT needed — the wireguard kernel module is loaded
# on the host (boot.kernelModules below); container just needs
# /lib/modules read-only to find it.
#
# ── auth: native OIDC against Pocket ID (v15.4.0+) ─────────────────────
#
# wg-easy's generic OIDC provider (`OAUTH_PROVIDERS=oidc`) is a Tier-1
# client: openid-client fetches discovery from OAUTH_OIDC_SERVER at
# request time (so no `sso.discoveryConsumers` entry — an IdP outage
# breaks the login page, not the container), PKCE S256, client secret
# via client_secret_post, `openid email profile`. The client secret is
# machine-generated by the identity provider's module and rendered in as
# OAUTH_OIDC_CLIENT_{ID,SECRET} through `consumers`. Two redirect URIs:
# /api/auth/oidc/callback (login) and /api/auth/oidc/link (attaching the
# provider to an already-signed-in account).
#
# Users match on the IdP `sub`, not on email, so the pre-OIDC local
# admin is a different account from the Pocket ID one. OAUTH_AUTO_REGISTER
# creates the latter at first login — "with Admin Permissions, as the
# permissions system is not yet implemented" (upstream's words), which
# is acceptable ONLY because the Pocket ID client is restricted to the
# `admins` group (ssoClients' default allowedGroups): nobody the IdP lets
# through this client is not already the operator. OAUTH_AUTO_LAUNCH
# sends /login straight to Pocket ID; `/login?auto_launch=false` shows
# the password form.
#
# DISABLE_PASSWORD_AUTH is on — set only once a Pocket ID login had
# succeeded, since upstream says to link an admin BEFORE disabling
# passwords. The pre-OIDC admin stays in wg-easy.db as
# dormant rows; INIT_USERNAME/INIT_PASSWORD (the host's env file) matter only for
# a fresh-bootstrap first init, which is why they are not removed.
# Break-glass on a fresh bootstrap: comment the flag out, rebuild, log in
# with INIT_*, let auto-register link the Pocket ID account, re-enable.
# The WireGuard tunnel itself never depends on any of this: :51820 is
# key-authenticated and stays up whether or not the UI can log in.
#
# The IdP side has one per-user requirement: wg-easy 401s
# "Email is not verified" unless userinfo carries email_verified=true,
# so every Pocket ID user that should reach this UI needs "Email
# verified" ticked.
#
# The host brings:
#   fleet.modules.wg-easy.enable       the switch (default off, as every catalog module)
#   fleet.modules.wg-easy.envSopsFile  INIT_USERNAME, INIT_PASSWORD (first-init admin)
#   fleet.images.wg-easy               the digest-pinned image
# The tunnel's public address is `fleet.wanHost`; the port (51820/udp) must be
# forwarded to the box by the router.

{
  config,
  lib,
  pkgs,
  mkRootlessContainer,
  mkDotenvSecret,
  pinnedImage,
  ...
}:

let
  cfg = config.fleet.modules.wg-easy;
  inherit (config.fleet.webApps.wg-easy) hostname;
in
{
  options.fleet.modules.wg-easy = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "wg-easy — WireGuard server and admin UI.";
    };

    envSopsFile = lib.mkOption {
      type = lib.types.path;
      example = lib.literalExpression "./host/sops/wg-easy/env.sops";
      description = ''
        sops-encrypted dotenv carrying INIT_USERNAME and INIT_PASSWORD, the
        local admin a fresh database is initialised with (the header says
        when it matters). Host data: the engine carries no box's ciphertext.
        Only read while the module is on.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # INIT_USERNAME + INIT_PASSWORD, decrypted to /run/secrets/wg-easy-env
    # at activation from the host's `envSopsFile`.
    sops.secrets."wg-easy-env" = mkDotenvSecret cfg.envSopsFile;

    # Pocket ID client — id `wg-easy`, secret generated on the box, rendered
    # into the container as the OAUTH_OIDC_* pair. PKCE stays on (default):
    # wg-easy sends S256. No `logo` here: the sync falls back to
    # `wg-easy.png` in the host's fleet.sso.logoDir, when it has one.
    fleet.ssoClients.wg-easy = {
      displayName = "WireGuard";
      description = "VPN — peers + profiles";
      launchURL = "https://${hostname}";
      callbackURLs = [
        "https://${hostname}/api/auth/oidc/callback"
        "https://${hostname}/api/auth/oidc/link"
      ];
      logoutCallbackURLs = [ "https://${hostname}/login" ];
      consumers = [ "wg-easy" ];
      consumerEnv = {
        id = "OAUTH_OIDC_CLIENT_ID";
        secret = "OAUTH_OIDC_CLIENT_SECRET";
      };
    };

    fleet.bridgeMemberships.wg-easy = [ "traefik" ];
    fleet.webApps.wg-easy = {
      serviceName = "wg-easy";
      port = 51821;
      metrics = {
        enable = true;
        path = "/metrics/prometheus";
      };
    };

    # A gluetun tunnel (platform/lib/gluetun-lib.nix) adds the same modules;
    # NixOS merges the lists.
    boot.kernelModules = [
      "wireguard"
      "iptable_nat"
      "iptable_filter"
    ];

    # The router forwards this port to the box — see fleet.directIngress. The
    # tunnel carries HTTP only, and WireGuard is UDP.
    fleet.directIngress.wireguard = {
      port = 51820;
      note = "A WireGuard socket does not answer an unauthenticated packet at all, which is the entire reason a forwarded port is acceptable here.";
    };

    networking.firewall.allowedUDPPorts = [ 51820 ];

    # ── the forwarded ports, at the LAN address, over the tunnel ──────────
    #
    # A peer at home types the LAN address (the WAN host resolves to it
    # through pi-hole), and so does a peer on the tunnel — but inside this
    # container's rootless netns the LAN address is the netns ITSELF (pasta
    # copies the host's address in), so a connection to it reaches only what
    # is published inside the netns: the bridge ports (80/443) answer, and a
    # port published on the host by its own pasta instance (a game server
    # kept off the bridge for its client addresses) is refused. The host is
    # 169.254.1.2 here, pasta's alias for it.
    #
    # So every port the router forwards (fleet.directIngress — the ones meant
    # to be reached from anywhere) that the netns does NOT already serve is
    # DNATed from the LAN address to that alias, exactly as the DNS hook does
    # for 10.8.0.1:53. A port a bridge member publishes is served in the
    # netns by rootlessport and already works; it is left alone rather than
    # rerouted. Converged after every container start; `-C` first, so a
    # re-run adds nothing twice.
    systemd.services.wg-easy-host-ports =
      let
        bridgePublished = lib.concatLists (
          lib.mapAttrsToList (
            n: c: if (config.fleet.bridgeMemberships.${n} or [ ]) != [ ] then c.ports else [ ]
          ) config.virtualisation.oci-containers.containers
        );
        # `[ip:]host:container[/proto]`, tcp when the proto is left out.
        publishes =
          i: p:
          let
            m = builtins.match "(.*:)?([0-9]+):[0-9]+(/(tcp|udp))?" p;
          in
          m != null
          && builtins.elemAt m 1 == toString i.port
          && (if builtins.elemAt m 3 == null then "tcp" else builtins.elemAt m 3) == i.proto;
        ports = lib.filter (
          i: !(i.port == 51820 && i.proto == "udp") && !lib.any (publishes i) bridgePublished
        ) (lib.attrValues config.fleet.directIngress);
        rule =
          i:
          "-d ${config.fleet.lanIp}/32 -i wg0 -p ${i.proto} -m ${i.proto} --dport ${toString i.port} -j DNAT --to-destination 169.254.1.2:${toString i.port}";
      in
      lib.mkIf (ports != [ ]) {
        description = "Reach the router-forwarded ports at the LAN address from the WireGuard tunnel";
        after = [ "podman-wg-easy.service" ];
        partOf = [ "podman-wg-easy.service" ];
        wantedBy = [
          "podman-wg-easy.service"
          "multi-user.target"
        ];
        path = [
          pkgs.podman
          pkgs.util-linux
          pkgs.coreutils
        ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          set -euo pipefail
          wg() {
            setpriv --reuid=${config.fleet.operator.user} --regid=${config.fleet.operator.group} --init-groups --inh-caps=-all \
              env HOME=${config.fleet.operator.home} XDG_RUNTIME_DIR=${config.fleet.operator.runtimeDir} \
              podman exec wg-easy iptables -t nat "$@"
          }
          for _ in $(seq 1 30); do
            wg -S PREROUTING > /dev/null 2>&1 && break
            sleep 2
          done
          ${lib.concatMapStrings (i: ''
            wg -C PREROUTING ${rule i} 2>/dev/null || wg -A PREROUTING ${rule i}
          '') ports}
          echo "tunnel reaches ${
            lib.concatMapStringsSep ", " (i: "${toString i.port}/${i.proto}") ports
          } at ${config.fleet.lanIp}"
        '';
      };

    fleet.statePaths = {
      # Non-traversable parent closes the world-readable window if wg-easy
      # rewrites its db loosely; container root maps to the operator, so the
      # bind mount still works.
      "${config.fleet.stateRoot}/wg-easy".mode = "0700";
      # wg-easy writes wg-easy.db (server private key + client configs/PSKs)
      # world-readable (0644). state-paths re-tightens it to 0600 at boot —
      # a private key has no business being world-readable, even on a
      # single-user box. (tmpfiles can't do this: it silently skips rules
      # under the operator-owned /home prefix. `f` pre-creates the file
      # empty if missing, which SQLite treats as a valid empty DB.)
      "${config.fleet.stateRoot}/wg-easy/wg-easy.db" = {
        type = "f";
        mode = "0600";
      };
    };

    virtualisation.oci-containers.containers.wg-easy = mkRootlessContainer {
      image = pinnedImage "wg-easy" "ghcr.io/wg-easy/wg-easy";

      ports = [
        "51820:51820/udp"
      ];

      volumes = [
        "${config.fleet.stateRoot}/wg-easy:/etc/wireguard"
        # NixOS keeps kernel modules under /run/booted-system, not
        # /lib/modules. Belt-and-suspenders bind (the module is loaded).
        "/run/booted-system/kernel-modules/lib/modules:/lib/modules:ro"
      ];

      environment = {
        INIT_ENABLED = "true";
        INIT_HOST = config.fleet.wanHost;
        INIT_PORT = "51820";
        # Client DNS must be the wg0 address (10.8.0.1), NOT a host IP:
        # - the LAN address is unreachable from the container netns (pasta
        #   copies the host IP into the namespace; port 53 has no netns
        #   listener, so queries die with "connection refused").
        # - 169.254.1.2 (pasta host alias) IS reachable from the netns,
        #   but clients never send it through the tunnel: 169.254/16 is
        #   link-local and stays pinned to the physical interface on
        #   macOS/iOS, beating the tunnel /1 routes.
        # A PostUp DNAT hook (stored in wg-easy.db, NOT re-created on a
        # fresh init — re-add via admin UI > Hooks if bootstrapping!)
        # forwards 10.8.0.1:53 -> 169.254.1.2:53 -> host pi-hole.
        INIT_DNS = "10.8.0.1";
        DISABLE_IPV6 = "true";

        # Pocket ID SSO — see the header. Client id/secret arrive via the
        # ssoClients consumer env file; everything non-secret is here.
        OAUTH_PROVIDERS = "oidc";
        OAUTH_OIDC_SERVER = config.fleet.sso.issuerUrl;
        OAUTH_OIDC_NAME = "Pocket ID";
        OAUTH_AUTO_REGISTER = "true";
        OAUTH_AUTO_LAUNCH = "oidc";
        DISABLE_PASSWORD_AUTH = "true";
      };

      # INIT_USERNAME + INIT_PASSWORD (first-init admin credentials; inert
      # once wg-easy.db exists). The OIDC client pair is appended by
      # the identity provider's client sync (pocket-id/clients.nix) via
      # `consumers` above.
      environmentFiles = [
        config.sops.secrets."wg-easy-env".path
      ];

      extraOptions = [
        "--cap-add=NET_ADMIN"
        "--cap-add=NET_RAW"
        "--sysctl=net.ipv4.ip_forward=1"
        "--sysctl=net.ipv4.conf.all.src_valid_mark=1"
      ];
    };
  };
}
